//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbOraRegaEntities : DbContext
    {
        public dbOraRegaEntities()
            : base("name=dbOraRegaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccessory> tblAccessories { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblBranchQueue> tblBranchQueues { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCompanyType> tblCompanyTypes { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmpDocument> tblEmpDocuments { get; set; }
        public virtual DbSet<tblEnquiryStatusMaster> tblEnquiryStatusMasters { get; set; }
        public virtual DbSet<tblHSNCodeGSTMapping> tblHSNCodeGSTMappings { get; set; }
        public virtual DbSet<tblIssueDescription> tblIssueDescriptions { get; set; }
        public virtual DbSet<tblLeaveType> tblLeaveTypes { get; set; }
        public virtual DbSet<tblMenuMaster> tblMenuMasters { get; set; }
        public virtual DbSet<tblMenuRoleMapping> tblMenuRoleMappings { get; set; }
        public virtual DbSet<tblOnlineCustomer> tblOnlineCustomers { get; set; }
        public virtual DbSet<tblOperatingSystem> tblOperatingSystems { get; set; }
        public virtual DbSet<tblOrderTypeMaster> tblOrderTypeMasters { get; set; }
        public virtual DbSet<tblPartDescription> tblPartDescriptions { get; set; }
        public virtual DbSet<tblPaymentTerm> tblPaymentTerms { get; set; }
        public virtual DbSet<tblPincode> tblPincodes { get; set; }
        public virtual DbSet<tblPriority> tblPriorities { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductCondition> tblProductConditions { get; set; }
        public virtual DbSet<tblProductMake> tblProductMakes { get; set; }
        public virtual DbSet<tblProductModel> tblProductModels { get; set; }
        public virtual DbSet<tblProductType> tblProductTypes { get; set; }
        public virtual DbSet<tblQueue> tblQueues { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblRoleHierarchy> tblRoleHierarchies { get; set; }
        public virtual DbSet<tblSalesOrderStatu> tblSalesOrderStatus { get; set; }
        public virtual DbSet<tblSOCustomerComment> tblSOCustomerComments { get; set; }
        public virtual DbSet<tblSOPOAttachment> tblSOPOAttachments { get; set; }
        public virtual DbSet<tblSOProductsMaster> tblSOProductsMasters { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblStockAndPartMapping> tblStockAndPartMappings { get; set; }
        public virtual DbSet<tblStockEntry> tblStockEntries { get; set; }
        public virtual DbSet<tblStockEntryHistory> tblStockEntryHistories { get; set; }
        public virtual DbSet<tblSupportType> tblSupportTypes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<tblWareHouseTransaction> tblWareHouseTransactions { get; set; }
        public virtual DbSet<tblWarrantyType> tblWarrantyTypes { get; set; }
        public virtual DbSet<tblWOAccessory> tblWOAccessories { get; set; }
        public virtual DbSet<tblWOProofOfPurchase> tblWOProofOfPurchases { get; set; }
        public virtual DbSet<tblWORepairRemark> tblWORepairRemarks { get; set; }
        public virtual DbSet<tblWOSnap> tblWOSnaps { get; set; }
        public virtual DbSet<tblStockEntryBulkData> tblStockEntryBulkDatas { get; set; }
        public virtual DbSet<tblLoggedInUser> tblLoggedInUsers { get; set; }
        public virtual DbSet<tblPermanentAddress> tblPermanentAddresses { get; set; }
        public virtual DbSet<tblTemporaryAddress> tblTemporaryAddresses { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<tblConfigurationMaster> tblConfigurationMasters { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblProductIssuesPhoto> tblProductIssuesPhotos { get; set; }
        public virtual DbSet<tblPurchaseProofPhoto> tblPurchaseProofPhotos { get; set; }
        public virtual DbSet<tblSalesOrderEnquiry> tblSalesOrderEnquiries { get; set; }
        public virtual DbSet<tblOrderStatusMaster> tblOrderStatusMasters { get; set; }
        public virtual DbSet<tblExtendedWarranty> tblExtendedWarranties { get; set; }
        public virtual DbSet<tblServiceAddresss> tblServiceAddressses { get; set; }
        public virtual DbSet<tblServiceType> tblServiceTypes { get; set; }
        public virtual DbSet<tblCustomerSellProductsMapping> tblCustomerSellProductsMappings { get; set; }
        public virtual DbSet<tblCustomersSellDetail> tblCustomersSellDetails { get; set; }
        public virtual DbSet<tblProductDetailsPurchaseProof> tblProductDetailsPurchaseProofs { get; set; }
        public virtual DbSet<tblProductDetailsSnap> tblProductDetailsSnaps { get; set; }
        public virtual DbSet<tblConfigContactU> tblConfigContactUs { get; set; }
        public virtual DbSet<tblExtendWarrantyPurchaseProof> tblExtendWarrantyPurchaseProofs { get; set; }
        public virtual DbSet<tblExtendedWarrantyProduct> tblExtendedWarrantyProducts { get; set; }
        public virtual DbSet<tblContactUsEnquiry> tblContactUsEnquiries { get; set; }
        public virtual DbSet<tblContactUsEnquiryPhoto> tblContactUsEnquiryPhotos { get; set; }
        public virtual DbSet<tblAddressTypesMaster> tblAddressTypesMasters { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<RoleMaster_Employee_Permission> RoleMaster_Employee_Permission { get; set; }
        public virtual DbSet<RoleMaster_Permission> RoleMaster_Permission { get; set; }
        public virtual DbSet<AttendanceHistory> AttendanceHistories { get; set; }
        public virtual DbSet<tblLeaveMaster> tblLeaveMasters { get; set; }
        public virtual DbSet<tblStatusMaster> tblStatusMasters { get; set; }
        public virtual DbSet<tblCareer> tblCareers { get; set; }
        public virtual DbSet<tblStockPartStatu> tblStockPartStatus { get; set; }
        public virtual DbSet<tblDelayType> tblDelayTypes { get; set; }
        public virtual DbSet<tblRepairClassType> tblRepairClassTypes { get; set; }
        public virtual DbSet<tblRescheduleReason> tblRescheduleReasons { get; set; }
        public virtual DbSet<tblTravelRange> tblTravelRanges { get; set; }
        public virtual DbSet<tblGSTMapping> tblGSTMappings { get; set; }
        public virtual DbSet<tblRatePerKM> tblRatePerKMs { get; set; }
        public virtual DbSet<tblProductDescription> tblProductDescriptions { get; set; }
        public virtual DbSet<tblCaseStatu> tblCaseStatus { get; set; }
        public virtual DbSet<tblWorkOrder> tblWorkOrders { get; set; }
        public virtual DbSet<tblBusinessType> tblBusinessTypes { get; set; }
        public virtual DbSet<tblPartDetail> tblPartDetails { get; set; }
        public virtual DbSet<tblWOPart> tblWOParts { get; set; }
        public virtual DbSet<tblWOOTPVerify> tblWOOTPVerifies { get; set; }
        public virtual DbSet<tblRequestForAdvance> tblRequestForAdvances { get; set; }
        public virtual DbSet<tblSOEnquiryProduct> tblSOEnquiryProducts { get; set; }
        public virtual DbSet<tblSalesOrderProduct> tblSalesOrderProducts { get; set; }
        public virtual DbSet<tblSalesOrder> tblSalesOrders { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblClaimSettlementItemAttachment> tblClaimSettlementItemAttachments { get; set; }
        public virtual DbSet<tblClaimSettlement> tblClaimSettlements { get; set; }
        public virtual DbSet<tblClaimSettlementItem> tblClaimSettlementItems { get; set; }
        public virtual DbSet<tblClaimType> tblClaimTypes { get; set; }
        public virtual DbSet<tblWorkOrderEnquiry> tblWorkOrderEnquiries { get; set; }
        public virtual DbSet<tblPartsAllocatedToEngineer> tblPartsAllocatedToEngineers { get; set; }
        public virtual DbSet<tblPartsAllocatedToWorkOrder> tblPartsAllocatedToWorkOrders { get; set; }
        public virtual DbSet<tblStockTransferStatu> tblStockTransferStatus { get; set; }
        public virtual DbSet<tblStockTransferOut> tblStockTransferOuts { get; set; }
        public virtual DbSet<tblSavedProductDetail> tblSavedProductDetails { get; set; }
        public virtual DbSet<tblWOEnquiryCustomerFeedback> tblWOEnquiryCustomerFeedbacks { get; set; }
        public virtual DbSet<tblPartsAllocatedToReturn> tblPartsAllocatedToReturns { get; set; }
        public virtual DbSet<tblBanner> tblBanners { get; set; }
        public virtual DbSet<tblOfferAd> tblOfferAds { get; set; }
        public virtual DbSet<tblOurProduct> tblOurProducts { get; set; }
        public virtual DbSet<tblOurService> tblOurServices { get; set; }
        public virtual DbSet<tblPaymentPolicy> tblPaymentPolicies { get; set; }
        public virtual DbSet<tblPrivacyAndPolicy> tblPrivacyAndPolicies { get; set; }
        public virtual DbSet<tblRefundAndCancellationPolicy> tblRefundAndCancellationPolicies { get; set; }
        public virtual DbSet<tblTermsAndCondition> tblTermsAndConditions { get; set; }
        public virtual DbSet<tblTestimonial> tblTestimonials { get; set; }
        public virtual DbSet<tblEngineerVisitHistory> tblEngineerVisitHistories { get; set; }
        public virtual DbSet<tblStockTransferPartDetail> tblStockTransferPartDetails { get; set; }
        public virtual DbSet<tblVehicleType> tblVehicleTypes { get; set; }
        public virtual DbSet<tblCareerPost> tblCareerPosts { get; set; }
        public virtual DbSet<tblTravelClaim> tblTravelClaims { get; set; }
        public virtual DbSet<tblStockOut_DAO> tblStockOut_DAO { get; set; }
        public virtual DbSet<tblStockOut_DAO_PartDetails> tblStockOut_DAO_PartDetails { get; set; }
        public virtual DbSet<tblStockOut_Defective> tblStockOut_Defective { get; set; }
        public virtual DbSet<tblStockOut_Defective_PartDetails> tblStockOut_Defective_PartDetails { get; set; }
        public virtual DbSet<tblTackingOrder> tblTackingOrders { get; set; }
    
        public virtual ObjectResult<GetEmployeeListForDropDown_Result> GetEmployeeListForDropDown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeListForDropDown_Result>("GetEmployeeListForDropDown");
        }
    
        public virtual ObjectResult<GetMenuList_Result> GetMenuList(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuList_Result>("GetMenuList", userIdParameter);
        }
    
        public virtual ObjectResult<GetProductMakesList_Result> GetProductMakesList(string productMake, string productType, string orderTypeCode, Nullable<bool> isActive)
        {
            var productMakeParameter = productMake != null ?
                new ObjectParameter("ProductMake", productMake) :
                new ObjectParameter("ProductMake", typeof(string));
    
            var productTypeParameter = productType != null ?
                new ObjectParameter("ProductType", productType) :
                new ObjectParameter("ProductType", typeof(string));
    
            var orderTypeCodeParameter = orderTypeCode != null ?
                new ObjectParameter("OrderTypeCode", orderTypeCode) :
                new ObjectParameter("OrderTypeCode", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductMakesList_Result>("GetProductMakesList", productMakeParameter, productTypeParameter, orderTypeCodeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetProductModelsList_Result> GetProductModelsList(string productModel, string productMake, string productType, string orderTypeCode, Nullable<bool> isActive)
        {
            var productModelParameter = productModel != null ?
                new ObjectParameter("ProductModel", productModel) :
                new ObjectParameter("ProductModel", typeof(string));
    
            var productMakeParameter = productMake != null ?
                new ObjectParameter("ProductMake", productMake) :
                new ObjectParameter("ProductMake", typeof(string));
    
            var productTypeParameter = productType != null ?
                new ObjectParameter("ProductType", productType) :
                new ObjectParameter("ProductType", typeof(string));
    
            var orderTypeCodeParameter = orderTypeCode != null ?
                new ObjectParameter("OrderTypeCode", orderTypeCode) :
                new ObjectParameter("OrderTypeCode", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductModelsList_Result>("GetProductModelsList", productModelParameter, productMakeParameter, productTypeParameter, orderTypeCodeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetProductTypesList_Result> GetProductTypesList(string productType, string orderTypeCode, Nullable<bool> isActive)
        {
            var productTypeParameter = productType != null ?
                new ObjectParameter("ProductType", productType) :
                new ObjectParameter("ProductType", typeof(string));
    
            var orderTypeCodeParameter = orderTypeCode != null ?
                new ObjectParameter("OrderTypeCode", orderTypeCode) :
                new ObjectParameter("OrderTypeCode", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductTypesList_Result>("GetProductTypesList", productTypeParameter, orderTypeCodeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetStockEntryList_Result> GetStockEntryList(Nullable<int> id, string docketNo, Nullable<int> companyId, Nullable<int> branchId, Nullable<int> vendorId, string uniqueCode, string partName, string partDescription, string partNumber, Nullable<System.DateTime> receivedDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var docketNoParameter = docketNo != null ?
                new ObjectParameter("DocketNo", docketNo) :
                new ObjectParameter("DocketNo", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            var uniqueCodeParameter = uniqueCode != null ?
                new ObjectParameter("UniqueCode", uniqueCode) :
                new ObjectParameter("UniqueCode", typeof(string));
    
            var partNameParameter = partName != null ?
                new ObjectParameter("PartName", partName) :
                new ObjectParameter("PartName", typeof(string));
    
            var partDescriptionParameter = partDescription != null ?
                new ObjectParameter("PartDescription", partDescription) :
                new ObjectParameter("PartDescription", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var receivedDateParameter = receivedDate.HasValue ?
                new ObjectParameter("ReceivedDate", receivedDate) :
                new ObjectParameter("ReceivedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockEntryList_Result>("GetStockEntryList", idParameter, docketNoParameter, companyIdParameter, branchIdParameter, vendorIdParameter, uniqueCodeParameter, partNameParameter, partDescriptionParameter, partNumberParameter, receivedDateParameter);
        }
    
        public virtual ObjectResult<GetVendorsList_Result> GetVendorsList(Nullable<int> countryId, Nullable<int> stateId, Nullable<int> cityId, Nullable<int> areaId, Nullable<bool> isActive)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("AreaId", areaId) :
                new ObjectParameter("AreaId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVendorsList_Result>("GetVendorsList", countryIdParameter, stateIdParameter, cityIdParameter, areaIdParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetWOListForDropDown_Result> GetWOListForDropDown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOListForDropDown_Result>("GetWOListForDropDown");
        }
    
        public virtual ObjectResult<GetWorkOrderCreationReport_Result> GetWorkOrderCreationReport(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> stateId, string branchIds)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var branchIdsParameter = branchIds != null ?
                new ObjectParameter("BranchIds", branchIds) :
                new ObjectParameter("BranchIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkOrderCreationReport_Result>("GetWorkOrderCreationReport", fromDateParameter, toDateParameter, stateIdParameter, branchIdsParameter);
        }
    
        public virtual ObjectResult<GetWorkOrderEnquiryReport_Result> GetWorkOrderEnquiryReport(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> stateId, string branchIds)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var branchIdsParameter = branchIds != null ?
                new ObjectParameter("BranchIds", branchIds) :
                new ObjectParameter("BranchIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkOrderEnquiryReport_Result>("GetWorkOrderEnquiryReport", fromDateParameter, toDateParameter, stateIdParameter, branchIdsParameter);
        }
    
        public virtual ObjectResult<ImportStockEntry_Result> ImportStockEntry(string stockEntryData, Nullable<long> loggedInUserId)
        {
            var stockEntryDataParameter = stockEntryData != null ?
                new ObjectParameter("StockEntryData", stockEntryData) :
                new ObjectParameter("StockEntryData", typeof(string));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ImportStockEntry_Result>("ImportStockEntry", stockEntryDataParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<ListWOForServiceEngineer_Result> ListWOForServiceEngineer(Nullable<int> orderStatusId, Nullable<int> engineerId)
        {
            var orderStatusIdParameter = orderStatusId.HasValue ?
                new ObjectParameter("OrderStatusId", orderStatusId) :
                new ObjectParameter("OrderStatusId", typeof(int));
    
            var engineerIdParameter = engineerId.HasValue ?
                new ObjectParameter("EngineerId", engineerId) :
                new ObjectParameter("EngineerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListWOForServiceEngineer_Result>("ListWOForServiceEngineer", orderStatusIdParameter, engineerIdParameter);
        }
    
        public virtual ObjectResult<GetLoggedInUserDetailsByToken_Result> GetLoggedInUserDetailsByToken(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLoggedInUserDetailsByToken_Result>("GetLoggedInUserDetailsByToken", tokenParameter);
        }
    
        public virtual ObjectResult<GetConfigurationsList_Result> GetConfigurationsList(string configKeys)
        {
            var configKeysParameter = configKeys != null ?
                new ObjectParameter("ConfigKeys", configKeys) :
                new ObjectParameter("ConfigKeys", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConfigurationsList_Result>("GetConfigurationsList", configKeysParameter);
        }
    
        public virtual ObjectResult<GetCustomerDetailsByMobile_Result> GetCustomerDetailsByMobile(string mobileNo)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerDetailsByMobile_Result>("GetCustomerDetailsByMobile", mobileNoParameter);
        }
    
        public virtual ObjectResult<GetProductModelDetails_Result> GetProductModelDetails(Nullable<int> prodModelId)
        {
            var prodModelIdParameter = prodModelId.HasValue ?
                new ObjectParameter("ProdModelId", prodModelId) :
                new ObjectParameter("ProdModelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductModelDetails_Result>("GetProductModelDetails", prodModelIdParameter);
        }
    
        public virtual ObjectResult<GetSalesOrdersList_Result> GetSalesOrdersList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> salesOrderStatusId, Nullable<int> loggedInUserId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var salesOrderStatusIdParameter = salesOrderStatusId.HasValue ?
                new ObjectParameter("SalesOrderStatusId", salesOrderStatusId) :
                new ObjectParameter("SalesOrderStatusId", typeof(int));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesOrdersList_Result>("GetSalesOrdersList", companyIdParameter, branchIdParameter, salesOrderStatusIdParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<GetSOCustomerCommentsList_Result> GetSOCustomerCommentsList(Nullable<int> salesOrderId)
        {
            var salesOrderIdParameter = salesOrderId.HasValue ?
                new ObjectParameter("SalesOrderId", salesOrderId) :
                new ObjectParameter("SalesOrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOCustomerCommentsList_Result>("GetSOCustomerCommentsList", salesOrderIdParameter);
        }
    
        public virtual ObjectResult<GetUsersAddresses_Result> GetUsersAddresses(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersAddresses_Result>("GetUsersAddresses", userIdParameter);
        }
    
        public virtual ObjectResult<GetSOEnquiriesListForCustomer_Result> GetSOEnquiriesListForCustomer(Nullable<int> loggedInUserId, Nullable<int> enquiryStatusId, string searchValue)
        {
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            var enquiryStatusIdParameter = enquiryStatusId.HasValue ?
                new ObjectParameter("EnquiryStatusId", enquiryStatusId) :
                new ObjectParameter("EnquiryStatusId", typeof(int));
    
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOEnquiriesListForCustomer_Result>("GetSOEnquiriesListForCustomer", loggedInUserIdParameter, enquiryStatusIdParameter, searchValueParameter);
        }
    
        public virtual ObjectResult<GetModuleMasterList_Result> GetModuleMasterList(string moduleName, string appType)
        {
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetModuleMasterList_Result>("GetModuleMasterList", moduleNameParameter, appTypeParameter);
        }
    
        public virtual ObjectResult<GetRoleDetailsById_Result> GetRoleDetailsById(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoleDetailsById_Result>("GetRoleDetailsById", idParameter);
        }
    
        public virtual ObjectResult<GetRoleMaster_PermissionList_Result> GetRoleMaster_PermissionList(Nullable<int> roleId, Nullable<int> employeeId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoleMaster_PermissionList_Result>("GetRoleMaster_PermissionList", roleIdParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<GetRoles_Result> GetRoles(string roleName)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoles_Result>("GetRoles", roleNameParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> SaveRoleDetails(Nullable<long> roleId, string roleName, Nullable<bool> isActive, Nullable<long> loggedInUserId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(long));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("SaveRoleDetails", roleIdParameter, roleNameParameter, isActiveParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> SaveRoleMaster_PermissionDetails(Nullable<long> rolePermissionId, Nullable<long> roleId, Nullable<long> moduleId, string appType, Nullable<bool> view, Nullable<bool> add, Nullable<bool> edit, Nullable<long> employeeId, Nullable<bool> isActive, Nullable<long> loggedInUserId)
        {
            var rolePermissionIdParameter = rolePermissionId.HasValue ?
                new ObjectParameter("RolePermissionId", rolePermissionId) :
                new ObjectParameter("RolePermissionId", typeof(long));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(long));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(long));
    
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            var viewParameter = view.HasValue ?
                new ObjectParameter("View", view) :
                new ObjectParameter("View", typeof(bool));
    
            var addParameter = add.HasValue ?
                new ObjectParameter("Add", add) :
                new ObjectParameter("Add", typeof(bool));
    
            var editParameter = edit.HasValue ?
                new ObjectParameter("Edit", edit) :
                new ObjectParameter("Edit", typeof(bool));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("SaveRoleMaster_PermissionDetails", rolePermissionIdParameter, roleIdParameter, moduleIdParameter, appTypeParameter, viewParameter, addParameter, editParameter, employeeIdParameter, isActiveParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<GetEmployeesListByRole_Result> GetEmployeesListByRole(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeesListByRole_Result>("GetEmployeesListByRole", empCodeParameter);
        }
    
        public virtual ObjectResult<GetAttendanceHistoryList_Result> GetAttendanceHistoryList(string employeeName, Nullable<System.DateTime> fromPunchInDate, Nullable<System.DateTime> toPunchInDate)
        {
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var fromPunchInDateParameter = fromPunchInDate.HasValue ?
                new ObjectParameter("FromPunchInDate", fromPunchInDate) :
                new ObjectParameter("FromPunchInDate", typeof(System.DateTime));
    
            var toPunchInDateParameter = toPunchInDate.HasValue ?
                new ObjectParameter("ToPunchInDate", toPunchInDate) :
                new ObjectParameter("ToPunchInDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAttendanceHistoryList_Result>("GetAttendanceHistoryList", employeeNameParameter, fromPunchInDateParameter, toPunchInDateParameter);
        }
    
        public virtual ObjectResult<GetLeaves_Result> GetLeaves(string employeeName, string leaveType, string leaveReason, Nullable<int> leaveStatusId, Nullable<bool> isActive, Nullable<int> loggedInUserId)
        {
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var leaveTypeParameter = leaveType != null ?
                new ObjectParameter("LeaveType", leaveType) :
                new ObjectParameter("LeaveType", typeof(string));
    
            var leaveReasonParameter = leaveReason != null ?
                new ObjectParameter("LeaveReason", leaveReason) :
                new ObjectParameter("LeaveReason", typeof(string));
    
            var leaveStatusIdParameter = leaveStatusId.HasValue ?
                new ObjectParameter("LeaveStatusId", leaveStatusId) :
                new ObjectParameter("LeaveStatusId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeaves_Result>("GetLeaves", employeeNameParameter, leaveTypeParameter, leaveReasonParameter, leaveStatusIdParameter, isActiveParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<GetLeaveDetailsById_Result> GetLeaveDetailsById(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeaveDetailsById_Result>("GetLeaveDetailsById", idParameter);
        }
    
        public virtual ObjectResult<GetBranchListByCompany_Result> GetBranchListByCompany(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBranchListByCompany_Result>("GetBranchListByCompany", idParameter);
        }
    
        public virtual ObjectResult<GetBranchListByState_Result> GetBranchListByState(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBranchListByState_Result>("GetBranchListByState", idParameter);
        }
    
        public virtual ObjectResult<GetAreaList_Result> GetAreaList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAreaList_Result>("GetAreaList");
        }
    
        public virtual ObjectResult<GetCityList_Result> GetCityList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityList_Result>("GetCityList");
        }
    
        public virtual ObjectResult<GetCountryList_Result> GetCountryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryList_Result>("GetCountryList");
        }
    
        public virtual ObjectResult<GetDepartmentList_Result> GetDepartmentList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentList_Result>("GetDepartmentList");
        }
    
        public virtual ObjectResult<GetPincodeList_Result> GetPincodeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPincodeList_Result>("GetPincodeList");
        }
    
        public virtual ObjectResult<GetStateList_Result> GetStateList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStateList_Result>("GetStateList");
        }
    
        public virtual ObjectResult<GetStockPartStatusList_Result> GetStockPartStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockPartStatusList_Result>("GetStockPartStatusList");
        }
    
        public virtual ObjectResult<GetDelayTypeList_Result> GetDelayTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDelayTypeList_Result>("GetDelayTypeList");
        }
    
        public virtual ObjectResult<GetRepairClassTypeList_Result> GetRepairClassTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRepairClassTypeList_Result>("GetRepairClassTypeList");
        }
    
        public virtual ObjectResult<GetRescheduleReasonList_Result> GetRescheduleReasonList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRescheduleReasonList_Result>("GetRescheduleReasonList");
        }
    
        public virtual ObjectResult<GetTravelRangeList_Result> GetTravelRangeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTravelRangeList_Result>("GetTravelRangeList");
        }
    
        public virtual ObjectResult<GetGSTMappingList_Result> GetGSTMappingList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGSTMappingList_Result>("GetGSTMappingList");
        }
    
        public virtual ObjectResult<GetRoleHierarchy_Result> GetRoleHierarchy(Nullable<int> reportingTo, Nullable<bool> isActive)
        {
            var reportingToParameter = reportingTo.HasValue ?
                new ObjectParameter("ReportingTo", reportingTo) :
                new ObjectParameter("ReportingTo", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoleHierarchy_Result>("GetRoleHierarchy", reportingToParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetAccessoriesList_Result> GetAccessoriesList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccessoriesList_Result>("GetAccessoriesList");
        }
    
        public virtual ObjectResult<GetCompanyTypeList_Result> GetCompanyTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompanyTypeList_Result>("GetCompanyTypeList");
        }
    
        public virtual ObjectResult<GetHSNCodeGSTMappingList_Result> GetHSNCodeGSTMappingList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHSNCodeGSTMappingList_Result>("GetHSNCodeGSTMappingList");
        }
    
        public virtual ObjectResult<GetIssueDescriptionList_Result> GetIssueDescriptionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIssueDescriptionList_Result>("GetIssueDescriptionList");
        }
    
        public virtual ObjectResult<GetLeaveTypeList_Result> GetLeaveTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeaveTypeList_Result>("GetLeaveTypeList");
        }
    
        public virtual ObjectResult<GetOperatingSystemList_Result> GetOperatingSystemList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOperatingSystemList_Result>("GetOperatingSystemList");
        }
    
        public virtual ObjectResult<GetPaymentTermsList_Result> GetPaymentTermsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentTermsList_Result>("GetPaymentTermsList");
        }
    
        public virtual ObjectResult<GetPriorityList_Result> GetPriorityList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPriorityList_Result>("GetPriorityList");
        }
    
        public virtual ObjectResult<GetSalesOrderStatusList_Result> GetSalesOrderStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesOrderStatusList_Result>("GetSalesOrderStatusList");
        }
    
        public virtual ObjectResult<GetSupportTypeList_Result> GetSupportTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSupportTypeList_Result>("GetSupportTypeList");
        }
    
        public virtual ObjectResult<GetWarrantyTypeList_Result> GetWarrantyTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWarrantyTypeList_Result>("GetWarrantyTypeList");
        }
    
        public virtual ObjectResult<GetRolesList_Result> GetRolesList(string roleName, Nullable<bool> isActive)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRolesList_Result>("GetRolesList", roleNameParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetReportingToEmployeeForSelectList_Result> GetReportingToEmployeeForSelectList(Nullable<long> roleId, Nullable<long> regionId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(long));
    
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportingToEmployeeForSelectList_Result>("GetReportingToEmployeeForSelectList", roleIdParameter, regionIdParameter);
        }
    
        public virtual ObjectResult<GetCustomerList_Result> GetCustomerList(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerList_Result>("GetCustomerList", customerIdParameter);
        }
    
        public virtual ObjectResult<GetGST_N_StateCode_ByCompanyNState_Result> GetGST_N_StateCode_ByCompanyNState(Nullable<int> companyId, Nullable<int> stateId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGST_N_StateCode_ByCompanyNState_Result>("GetGST_N_StateCode_ByCompanyNState", companyIdParameter, stateIdParameter);
        }
    
        public virtual ObjectResult<GetProductDescriptionList_Result> GetProductDescriptionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDescriptionList_Result>("GetProductDescriptionList");
        }
    
        public virtual ObjectResult<GetWOEnquiryDetailsForCustomer_Result> GetWOEnquiryDetailsForCustomer(Nullable<int> customerId, Nullable<int> wOEnquiryId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var wOEnquiryIdParameter = wOEnquiryId.HasValue ?
                new ObjectParameter("WOEnquiryId", wOEnquiryId) :
                new ObjectParameter("WOEnquiryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOEnquiryDetailsForCustomer_Result>("GetWOEnquiryDetailsForCustomer", customerIdParameter, wOEnquiryIdParameter);
        }
    
        public virtual ObjectResult<GetSOEnquiryDetailsForCustomer_Result> GetSOEnquiryDetailsForCustomer(Nullable<int> customerId, Nullable<int> sOEnquiryId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var sOEnquiryIdParameter = sOEnquiryId.HasValue ?
                new ObjectParameter("SOEnquiryId", sOEnquiryId) :
                new ObjectParameter("SOEnquiryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOEnquiryDetailsForCustomer_Result>("GetSOEnquiryDetailsForCustomer", customerIdParameter, sOEnquiryIdParameter);
        }
    
        public virtual ObjectResult<GetCaseStatusList_Result> GetCaseStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCaseStatusList_Result>("GetCaseStatusList");
        }
    
        public virtual ObjectResult<GetBusinessType_Result> GetBusinessType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBusinessType_Result>("GetBusinessType");
        }
    
        public virtual ObjectResult<GetEmployeesList_Result> GetEmployeesList(string empCode, string empName, string email, Nullable<bool> isActive)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeesList_Result>("GetEmployeesList", empCodeParameter, empNameParameter, emailParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetWorkOrderDetails_Result> GetWorkOrderDetails(string workOrderNumber)
        {
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkOrderDetails_Result>("GetWorkOrderDetails", workOrderNumberParameter);
        }
    
        public virtual ObjectResult<GetRequestForAdvanceList_Result> GetRequestForAdvanceList(Nullable<int> employeeId, string claimId, Nullable<int> advanceStatusId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var claimIdParameter = claimId != null ?
                new ObjectParameter("ClaimId", claimId) :
                new ObjectParameter("ClaimId", typeof(string));
    
            var advanceStatusIdParameter = advanceStatusId.HasValue ?
                new ObjectParameter("AdvanceStatusId", advanceStatusId) :
                new ObjectParameter("AdvanceStatusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestForAdvanceList_Result>("GetRequestForAdvanceList", employeeIdParameter, claimIdParameter, advanceStatusIdParameter);
        }
    
        public virtual ObjectResult<GetWOEnquiriesListForCustomer_Result> GetWOEnquiriesListForCustomer(Nullable<int> loggedInUserId, Nullable<int> enquiryStatusId, string searchValue)
        {
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            var enquiryStatusIdParameter = enquiryStatusId.HasValue ?
                new ObjectParameter("EnquiryStatusId", enquiryStatusId) :
                new ObjectParameter("EnquiryStatusId", typeof(int));
    
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOEnquiriesListForCustomer_Result>("GetWOEnquiriesListForCustomer", loggedInUserIdParameter, enquiryStatusIdParameter, searchValueParameter);
        }
    
        public virtual ObjectResult<GetSalesOrderDetails_Result> GetSalesOrderDetails(string salesOrderNo)
        {
            var salesOrderNoParameter = salesOrderNo != null ?
                new ObjectParameter("SalesOrderNo", salesOrderNo) :
                new ObjectParameter("SalesOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesOrderDetails_Result>("GetSalesOrderDetails", salesOrderNoParameter);
        }
    
        public virtual ObjectResult<GetRoleMaster_EmployeePermissionList_Result> GetRoleMaster_EmployeePermissionList(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoleMaster_EmployeePermissionList_Result>("GetRoleMaster_EmployeePermissionList", employeeIdParameter);
        }
    
        public virtual ObjectResult<GetBranchList_Result> GetBranchList(Nullable<int> companyId, Nullable<int> branchId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBranchList_Result>("GetBranchList", companyIdParameter, branchIdParameter);
        }
    
        public virtual ObjectResult<GetCompanyList_Result> GetCompanyList(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompanyList_Result>("GetCompanyList", companyIdParameter);
        }
    
        public virtual ObjectResult<GetClaimSettlementItemAttachmentById_Result> GetClaimSettlementItemAttachmentById(Nullable<int> claimSettlementItemId)
        {
            var claimSettlementItemIdParameter = claimSettlementItemId.HasValue ?
                new ObjectParameter("ClaimSettlementItemId", claimSettlementItemId) :
                new ObjectParameter("ClaimSettlementItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClaimSettlementItemAttachmentById_Result>("GetClaimSettlementItemAttachmentById", claimSettlementItemIdParameter);
        }
    
        public virtual ObjectResult<GetClaimSettlementItemById_Result> GetClaimSettlementItemById(Nullable<int> claimSettlementId)
        {
            var claimSettlementIdParameter = claimSettlementId.HasValue ?
                new ObjectParameter("ClaimSettlementId", claimSettlementId) :
                new ObjectParameter("ClaimSettlementId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClaimSettlementItemById_Result>("GetClaimSettlementItemById", claimSettlementIdParameter);
        }
    
        public virtual ObjectResult<GetSOEnquiryProductsList_Result> GetSOEnquiryProductsList(Nullable<int> sOEnquiryId)
        {
            var sOEnquiryIdParameter = sOEnquiryId.HasValue ?
                new ObjectParameter("SOEnquiryId", sOEnquiryId) :
                new ObjectParameter("SOEnquiryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOEnquiryProductsList_Result>("GetSOEnquiryProductsList", sOEnquiryIdParameter);
        }
    
        public virtual ObjectResult<GetWorkOrderEnquiriesList_Result> GetWorkOrderEnquiriesList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> enquiryStatusId, Nullable<int> loggedInUserId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var enquiryStatusIdParameter = enquiryStatusId.HasValue ?
                new ObjectParameter("EnquiryStatusId", enquiryStatusId) :
                new ObjectParameter("EnquiryStatusId", typeof(int));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkOrderEnquiriesList_Result>("GetWorkOrderEnquiriesList", companyIdParameter, branchIdParameter, enquiryStatusIdParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<GetSalesOrderProductsList_Result> GetSalesOrderProductsList(Nullable<int> salesOrderId)
        {
            var salesOrderIdParameter = salesOrderId.HasValue ?
                new ObjectParameter("SalesOrderId", salesOrderId) :
                new ObjectParameter("SalesOrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesOrderProductsList_Result>("GetSalesOrderProductsList", salesOrderIdParameter);
        }
    
        public virtual ObjectResult<GetClaimSettlementList_Result> GetClaimSettlementList(Nullable<int> claimSattlementId, Nullable<int> employeeId, string claimId, Nullable<int> settlementStatusId)
        {
            var claimSattlementIdParameter = claimSattlementId.HasValue ?
                new ObjectParameter("ClaimSattlementId", claimSattlementId) :
                new ObjectParameter("ClaimSattlementId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var claimIdParameter = claimId != null ?
                new ObjectParameter("ClaimId", claimId) :
                new ObjectParameter("ClaimId", typeof(string));
    
            var settlementStatusIdParameter = settlementStatusId.HasValue ?
                new ObjectParameter("SettlementStatusId", settlementStatusId) :
                new ObjectParameter("SettlementStatusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClaimSettlementList_Result>("GetClaimSettlementList", claimSattlementIdParameter, employeeIdParameter, claimIdParameter, settlementStatusIdParameter);
        }
    
        public virtual ObjectResult<GetStockTransferList_Result> GetStockTransferList(string dockerNo, Nullable<int> userid)
        {
            var dockerNoParameter = dockerNo != null ?
                new ObjectParameter("DockerNo", dockerNo) :
                new ObjectParameter("DockerNo", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockTransferList_Result>("GetStockTransferList", dockerNoParameter, useridParameter);
        }
    
        public virtual ObjectResult<GetStockTransferInOutByChallanNumber_Result> GetStockTransferInOutByChallanNumber(string challanNumber)
        {
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockTransferInOutByChallanNumber_Result>("GetStockTransferInOutByChallanNumber", challanNumberParameter);
        }
    
        public virtual ObjectResult<GetStockTransferInChallanList_Result> GetStockTransferInChallanList(Nullable<int> companyId, Nullable<int> branchId, string challanNumber, string dockerNo, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            var dockerNoParameter = dockerNo != null ?
                new ObjectParameter("DockerNo", dockerNo) :
                new ObjectParameter("DockerNo", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockTransferInChallanList_Result>("GetStockTransferInChallanList", companyIdParameter, branchIdParameter, challanNumberParameter, dockerNoParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetRatePerKMList_Result> GetRatePerKMList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRatePerKMList_Result>("GetRatePerKMList");
        }
    
        public virtual ObjectResult<GetVehicleTypeList_Result> GetVehicleTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVehicleTypeList_Result>("GetVehicleTypeList");
        }
    
        public virtual ObjectResult<GetBannerList_Result> GetBannerList(string appType, Nullable<bool> isActive)
        {
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBannerList_Result>("GetBannerList", appTypeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetOfferAdsList_Result> GetOfferAdsList(string appType, Nullable<bool> isActive)
        {
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOfferAdsList_Result>("GetOfferAdsList", appTypeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetOurProductList_Result> GetOurProductList(string appType, Nullable<bool> isActive)
        {
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOurProductList_Result>("GetOurProductList", appTypeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetOurServiceList_Result> GetOurServiceList(string appType, Nullable<bool> isActive)
        {
            var appTypeParameter = appType != null ?
                new ObjectParameter("AppType", appType) :
                new ObjectParameter("AppType", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOurServiceList_Result>("GetOurServiceList", appTypeParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<GetPaymentPolicyList_Result> GetPaymentPolicyList(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentPolicyList_Result>("GetPaymentPolicyList", isActiveParameter);
        }
    
        public virtual ObjectResult<GetPrivacyAndPolicyList_Result> GetPrivacyAndPolicyList(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrivacyAndPolicyList_Result>("GetPrivacyAndPolicyList", isActiveParameter);
        }
    
        public virtual ObjectResult<GetRefundAndCancellationPolicyList_Result> GetRefundAndCancellationPolicyList(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRefundAndCancellationPolicyList_Result>("GetRefundAndCancellationPolicyList", isActiveParameter);
        }
    
        public virtual ObjectResult<GetTermsAndConditionList_Result> GetTermsAndConditionList(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTermsAndConditionList_Result>("GetTermsAndConditionList", isActiveParameter);
        }
    
        public virtual ObjectResult<GetTestimonialList_Result> GetTestimonialList(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTestimonialList_Result>("GetTestimonialList", isActiveParameter);
        }
    
        public virtual ObjectResult<GetEngineerVisitHistoryList_Result> GetEngineerVisitHistoryList(Nullable<int> engineerId, string workOrderNumber)
        {
            var engineerIdParameter = engineerId.HasValue ?
                new ObjectParameter("EngineerId", engineerId) :
                new ObjectParameter("EngineerId", typeof(int));
    
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEngineerVisitHistoryList_Result>("GetEngineerVisitHistoryList", engineerIdParameter, workOrderNumberParameter);
        }
    
        public virtual ObjectResult<GetTravelClaimList_Result> GetTravelClaimList(Nullable<int> employeeId, string workOrderNumber, Nullable<int> statusId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTravelClaimList_Result>("GetTravelClaimList", employeeIdParameter, workOrderNumberParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<GetPartDetailTransferHistoryLogList_Result> GetPartDetailTransferHistoryLogList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> partId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var partIdParameter = partId.HasValue ?
                new ObjectParameter("PartId", partId) :
                new ObjectParameter("PartId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartDetailTransferHistoryLogList_Result>("GetPartDetailTransferHistoryLogList", companyIdParameter, branchIdParameter, partIdParameter);
        }
    
        public virtual ObjectResult<GetStockTransferInList_Result> GetStockTransferInList(string challanNo)
        {
            var challanNoParameter = challanNo != null ?
                new ObjectParameter("ChallanNo", challanNo) :
                new ObjectParameter("ChallanNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockTransferInList_Result>("GetStockTransferInList", challanNoParameter);
        }
    
        public virtual ObjectResult<GetWOCustomerFeedbackList_Result> GetWOCustomerFeedbackList(string workOrderNo)
        {
            var workOrderNoParameter = workOrderNo != null ?
                new ObjectParameter("WorkOrderNo", workOrderNo) :
                new ObjectParameter("WorkOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOCustomerFeedbackList_Result>("GetWOCustomerFeedbackList", workOrderNoParameter);
        }
    
        public virtual ObjectResult<GetPartDetailList_Result> GetPartDetailList(Nullable<int> id, Nullable<int> companyId, Nullable<int> branchId, Nullable<int> userId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartDetailList_Result>("GetPartDetailList", idParameter, companyIdParameter, branchIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetPartsListForAllocation_Result> GetPartsListForAllocation(Nullable<int> companyId, Nullable<int> branchId, string uniqueCode, string partNumber, string partDesc, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var uniqueCodeParameter = uniqueCode != null ?
                new ObjectParameter("UniqueCode", uniqueCode) :
                new ObjectParameter("UniqueCode", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var partDescParameter = partDesc != null ?
                new ObjectParameter("PartDesc", partDesc) :
                new ObjectParameter("PartDesc", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsListForAllocation_Result>("GetPartsListForAllocation", companyIdParameter, branchIdParameter, uniqueCodeParameter, partNumberParameter, partDescParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockAllocationToWorkOrderList_Result> GetStockAllocationToWorkOrderList(Nullable<int> companyId, Nullable<int> branchId, string workOrderNo, string partNumber, string partDesc, Nullable<int> allocatedBy, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var workOrderNoParameter = workOrderNo != null ?
                new ObjectParameter("WorkOrderNo", workOrderNo) :
                new ObjectParameter("WorkOrderNo", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var partDescParameter = partDesc != null ?
                new ObjectParameter("PartDesc", partDesc) :
                new ObjectParameter("PartDesc", typeof(string));
    
            var allocatedByParameter = allocatedBy.HasValue ?
                new ObjectParameter("AllocatedBy", allocatedBy) :
                new ObjectParameter("AllocatedBy", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockAllocationToWorkOrderList_Result>("GetStockAllocationToWorkOrderList", companyIdParameter, branchIdParameter, workOrderNoParameter, partNumberParameter, partDescParameter, allocatedByParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockAllocationToEngineerList_Result> GetStockAllocationToEngineerList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> engineerId, string engineerName, string partNumber, string partDesc, string type, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var engineerIdParameter = engineerId.HasValue ?
                new ObjectParameter("EngineerId", engineerId) :
                new ObjectParameter("EngineerId", typeof(int));
    
            var engineerNameParameter = engineerName != null ?
                new ObjectParameter("EngineerName", engineerName) :
                new ObjectParameter("EngineerName", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var partDescParameter = partDesc != null ?
                new ObjectParameter("PartDesc", partDesc) :
                new ObjectParameter("PartDesc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockAllocationToEngineerList_Result>("GetStockAllocationToEngineerList", companyIdParameter, branchIdParameter, engineerIdParameter, engineerNameParameter, partNumberParameter, partDescParameter, typeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockAllocationToReturnList_Result> GetStockAllocationToReturnList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> engineerId, string engineerName, string partNumber, string partDesc, Nullable<int> statusId, string type, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var engineerIdParameter = engineerId.HasValue ?
                new ObjectParameter("EngineerId", engineerId) :
                new ObjectParameter("EngineerId", typeof(int));
    
            var engineerNameParameter = engineerName != null ?
                new ObjectParameter("EngineerName", engineerName) :
                new ObjectParameter("EngineerName", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var partDescParameter = partDesc != null ?
                new ObjectParameter("PartDesc", partDesc) :
                new ObjectParameter("PartDesc", typeof(string));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockAllocationToReturnList_Result>("GetStockAllocationToReturnList", companyIdParameter, branchIdParameter, engineerIdParameter, engineerNameParameter, partNumberParameter, partDescParameter, statusIdParameter, typeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockTransferOutChallanList_Result> GetStockTransferOutChallanList(Nullable<int> companyId, Nullable<int> branchId, string challanNumber, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockTransferOutChallanList_Result>("GetStockTransferOutChallanList", companyIdParameter, branchIdParameter, challanNumberParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetSOEnquiryList_Result> GetSOEnquiryList(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> enquiryStatusId, Nullable<int> loggedInUserId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var enquiryStatusIdParameter = enquiryStatusId.HasValue ?
                new ObjectParameter("EnquiryStatusId", enquiryStatusId) :
                new ObjectParameter("EnquiryStatusId", typeof(int));
    
            var loggedInUserIdParameter = loggedInUserId.HasValue ?
                new ObjectParameter("LoggedInUserId", loggedInUserId) :
                new ObjectParameter("LoggedInUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOEnquiryList_Result>("GetSOEnquiryList", companyIdParameter, branchIdParameter, enquiryStatusIdParameter, loggedInUserIdParameter);
        }
    
        public virtual ObjectResult<GetWorkOrderList_Result> GetWorkOrderList(Nullable<int> companyId, Nullable<int> branchId, string workOrderNumber, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkOrderList_Result>("GetWorkOrderList", companyIdParameter, branchIdParameter, workOrderNumberParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetWOListForEmployees_Result> GetWOListForEmployees(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> orderStatusId, Nullable<int> engineerId, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var orderStatusIdParameter = orderStatusId.HasValue ?
                new ObjectParameter("OrderStatusId", orderStatusId) :
                new ObjectParameter("OrderStatusId", typeof(int));
    
            var engineerIdParameter = engineerId.HasValue ?
                new ObjectParameter("EngineerId", engineerId) :
                new ObjectParameter("EngineerId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOListForEmployees_Result>("GetWOListForEmployees", companyIdParameter, branchIdParameter, orderStatusIdParameter, engineerIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockOut_Defective_ChallanList_Result> GetStockOut_Defective_ChallanList(Nullable<int> companyId, Nullable<int> branchId, string challanNumber, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockOut_Defective_ChallanList_Result>("GetStockOut_Defective_ChallanList", companyIdParameter, branchIdParameter, challanNumberParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockOut_DAO_ChallanList_Result> GetStockOut_DAO_ChallanList(Nullable<int> companyId, Nullable<int> branchId, string challanNumber, Nullable<int> userId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockOut_DAO_ChallanList_Result>("GetStockOut_DAO_ChallanList", companyIdParameter, branchIdParameter, challanNumberParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetStockOutDefectiveByChallanNumber_Result> GetStockOutDefectiveByChallanNumber(string challanNumber)
        {
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockOutDefectiveByChallanNumber_Result>("GetStockOutDefectiveByChallanNumber", challanNumberParameter);
        }
    
        public virtual ObjectResult<GetStockOutDOAByChallanNumber_Result> GetStockOutDOAByChallanNumber(string challanNumber)
        {
            var challanNumberParameter = challanNumber != null ?
                new ObjectParameter("ChallanNumber", challanNumber) :
                new ObjectParameter("ChallanNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockOutDOAByChallanNumber_Result>("GetStockOutDOAByChallanNumber", challanNumberParameter);
        }
    
        public virtual ObjectResult<GetEngineerList_Result> GetEngineerList(Nullable<int> companyId, Nullable<int> branchId, string userType)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEngineerList_Result>("GetEngineerList", companyIdParameter, branchIdParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<GetTackingOrderLog_Result> GetTackingOrderLog(string module, Nullable<int> moduleUniqId)
        {
            var moduleParameter = module != null ?
                new ObjectParameter("Module", module) :
                new ObjectParameter("Module", typeof(string));
    
            var moduleUniqIdParameter = moduleUniqId.HasValue ?
                new ObjectParameter("ModuleUniqId", moduleUniqId) :
                new ObjectParameter("ModuleUniqId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTackingOrderLog_Result>("GetTackingOrderLog", moduleParameter, moduleUniqIdParameter);
        }
    }
}
