//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLD_tblWorkOrderEnquiry
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAdderss { get; set; }
        public string AlternateNumber { get; set; }
        public string GSTNumber { get; set; }
        public string PanNumber { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<int> ProductDescriptionId { get; set; }
        public string ProductSerialNumber { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
        public string WarrantyNumber { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> OperatingSystemId { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PincodeId { get; set; }
        public Nullable<int> IssueDescriptionId { get; set; }
        public string IssueReported { get; set; }
        public Nullable<int> SourceChannelId { get; set; }
        public string EnquiryStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProductModelId { get; set; }
        public string EnquiryIssueDescription { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string VisitingAddress { get; set; }
        public Nullable<int> VisitStateId { get; set; }
        public Nullable<int> VisitCityId { get; set; }
        public Nullable<int> VisitAreaId { get; set; }
        public Nullable<int> VisitPincodeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string OrganizationName { get; set; }
    }
}
