//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAMCReminderEmail
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string AMCYear { get; set; }
        public string AMCStartDate_EndDate_LastEmailDate { get; set; }
        public Nullable<int> AMCRemainingDays { get; set; }
        public Nullable<int> AMCReminderCount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
