//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCareerPost
    {
        public int CareerPostId { get; set; }
        public string JobTitle { get; set; }
        public string RequiredExp { get; set; }
        public string Vacancies { get; set; }
        public string JobLocation { get; set; }
        public string JobDetails { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
