//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomersSellDetail
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string AlternateMobileNo { get; set; }
        public string CustomerGstNo { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ServiceAddressId { get; set; }
    }
}
