//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCareer
    {
        public int CareerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public string Position { get; set; }
        public string TotalExperience { get; set; }
        public string Gender { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string NoticePeriod { get; set; }
        public string ResumeFilePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
    }
}
