//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactUsEnquiryPhoto
    {
        public long Id { get; set; }
        public long ContactUsId { get; set; }
        public string FilesOriginalName { get; set; }
        public string FilePath { get; set; }
        public bool IsDeleted { get; set; }
    }
}
