//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyTypeId { get; set; }
        public string RegistrationNumber { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string CompanyLogo { get; set; }
        public string TaxNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PincodeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyLogoPath { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string GSTNumber { get; set; }
        public string PANNumber { get; set; }
        public int BranchAdd { get; set; }
    }
}
