//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpense
    {
        public int Id { get; set; }
        public string ExpenseId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> AmountPerKM { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
