//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailNotification
    {
        public long Id { get; set; }
        public string Module { get; set; }
        public string Subject { get; set; }
        public string SendTo { get; set; }
        public string Content { get; set; }
        public string EmailTo { get; set; }
        public bool IsSent { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string RefValue1 { get; set; }
        public string RefValue2 { get; set; }
    }
}
