//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExtendedWarrantyProduct
    {
        public int Id { get; set; }
        public Nullable<int> ProductModelId { get; set; }
        public string ProductSerialNo { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
        public Nullable<int> ProductConditionId { get; set; }
        public string ProdModelIfOther { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductMakeId { get; set; }
    }
}
