//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMenuMaster()
        {
            this.tblMenuRoleMappings = new HashSet<tblMenuRoleMapping>();
        }
    
        public int MenuId { get; set; }
        public string MenuTitle { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<bool> IsMasterMenu { get; set; }
        public Nullable<int> PerentMenuId { get; set; }
        public Nullable<bool> IsSuperAdminMenu { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> SequanceNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMenuRoleMapping> tblMenuRoleMappings { get; set; }
    }
}
