//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public string SendTo { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerMessage { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string EmployeeMessage { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool ReadUnread { get; set; }
        public string RefValue1 { get; set; }
        public string RefValue2 { get; set; }
    }
}
