//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductIssuesPhoto
    {
        public int Id { get; set; }
        public string PhotoPath { get; set; }
        public int WOEnquiryId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FilesOriginalName { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
    }
}
