//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentPartDetail
    {
        public int Id { get; set; }
        public Nullable<long> PaymentId { get; set; }
        public Nullable<long> PartId { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
    }
}
