//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartDetail
    {
        public int Id { get; set; }
        public string UniqueCode { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public Nullable<int> HSNCodeId { get; set; }
        public string CTSerialNo { get; set; }
        public int PartStatusId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string ReceiveFrom { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string DocketNo { get; set; }
        public Nullable<int> StockPartStatusId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
