//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int Id { get; set; }
        public string QuotationNumber { get; set; }
        public string MerchantTransactionId { get; set; }
        public string TransactionId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<bool> IsAdvance { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountInPaisa { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentMessage { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsRefund { get; set; }
        public string Refund_MerchantTransactionId { get; set; }
        public string Refund_TransactionId { get; set; }
        public Nullable<decimal> Refund_Amount { get; set; }
        public Nullable<decimal> Refund_AmountInPaisa { get; set; }
        public Nullable<bool> Refund_IsRefundSuccess { get; set; }
        public string Refund_PaymentStatus { get; set; }
        public string Refund_PaymentMessage { get; set; }
        public string Refund_RequestJson { get; set; }
        public string Refund_ResponseJson { get; set; }
        public string Refund_Error { get; set; }
        public Nullable<System.DateTime> Refund_CreatedDate { get; set; }
        public Nullable<int> Refund_CreatedBy { get; set; }
        public Nullable<System.DateTime> Refund_ModifiedDate { get; set; }
        public Nullable<int> Refund_ModifiedBy { get; set; }
    }
}
