//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public int Id { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public string QuotationNumber { get; set; }
        public int WorkOrderId { get; set; }
        public Nullable<decimal> AmountBeforeTax { get; set; }
        public Nullable<int> CGSTPerct { get; set; }
        public Nullable<decimal> CGSTValue { get; set; }
        public Nullable<int> SGSTPerct { get; set; }
        public Nullable<decimal> SGSTValue { get; set; }
        public Nullable<int> IGSTPerct { get; set; }
        public Nullable<decimal> IGSTValue { get; set; }
        public Nullable<decimal> GrossAmountIncludeTax { get; set; }
        public Nullable<decimal> TotalDiscAmt { get; set; }
        public Nullable<decimal> AdvanceReceived { get; set; }
        public Nullable<decimal> AmountPaidAfter { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public string Reason { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
