//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrder
    {
        public int Id { get; set; }
        public string SalesOrderNumber { get; set; }
        public System.DateTime TicketLogDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string AlternateNumber { get; set; }
        public string GstNumber { get; set; }
        public Nullable<int> CustomerAddressId { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public Nullable<int> IssueDescId { get; set; }
        public Nullable<int> SalesOrderStatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SOEnquiryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CustomerComment { get; set; }
    }
}
