//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMSLogHistory
    {
        public int Id { get; set; }
        public Nullable<int> OTPId { get; set; }
        public string TemplateName { get; set; }
        public string Mobile { get; set; }
        public string TemplateContent { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalNumberSubmitted { get; set; }
        public Nullable<int> CampgId { get; set; }
        public string LogId { get; set; }
        public Nullable<int> Code { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
