//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockOut_DAO_PartDetails
    {
        public int Id { get; set; }
        public Nullable<int> StockOut_DAOId { get; set; }
        public string DocketNo { get; set; }
        public Nullable<int> PartId { get; set; }
    }
}
