//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrderEnquiry
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string AlternateMobileNo { get; set; }
        public string CustomerGstNo { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public string EnquiryComment { get; set; }
        public Nullable<int> EnquiryStatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CustomerAddressId { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string CustomerPanNo { get; set; }
        public Nullable<int> IssueDescId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
