//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockEntryBulkData
    {
        public System.Guid FileId { get; set; }
        public string DocketNo { get; set; }
        public string ReceivedFrom { get; set; }
        public string CompanyName { get; set; }
        public string Branch { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public string HSNCode { get; set; }
        public string CTSerialNo { get; set; }
        public string PartStatus { get; set; }
        public Nullable<int> InQuantity { get; set; }
        public bool IsValid { get; set; }
        public string ValidationMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PartDetailUniqueCode { get; set; }
    }
}
