//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatusMaster
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string StatusCode { get; set; }
        public string Notes { get; set; }
    }
}
