//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSavedProductDetail
    {
        public long Id { get; set; }
        public Nullable<int> ProdModelId { get; set; }
        public string ProdSerialNo { get; set; }
        public string ProdNumber { get; set; }
        public Nullable<int> ProdDescId { get; set; }
        public Nullable<int> ProdConditionId { get; set; }
        public string ProdDescIfOther { get; set; }
        public string ProdModelIfOther { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductMakeId { get; set; }
    }
}
