//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWOPartRequest
    {
        public int Id { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string PartDesc { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
