//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWOEnquiryCustomerFeedback
    {
        public int Id { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> OverallExperience { get; set; }
        public string HelpUsToImproveMore { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
