//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder
    {
        public int Id { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<int> SupportTypeId { get; set; }
        public Nullable<System.DateTime> TicketLogDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string PanNumber { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string AlternateNumber { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductDescriptionId { get; set; }
        public string ProductNumber { get; set; }
        public string ProductSerialNumber { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
        public string WarrantyNumber { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> OperatingSystemId { get; set; }
        public string ReportedIssue { get; set; }
        public string MiscellaneousRemark { get; set; }
        public Nullable<int> IssueDescriptionId { get; set; }
        public string EngineerDiagnosis { get; set; }
        public Nullable<int> EngineerId { get; set; }
        public string DigitUEFIFailureID { get; set; }
        public string CustomerComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int CustomerId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<int> WorkOrderEnquiryId { get; set; }
        public int ServiceAddressId { get; set; }
        public Nullable<int> ProductMakeId { get; set; }
        public Nullable<int> ProductModelId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string ResolutionSummary { get; set; }
        public Nullable<int> DelayTypeId { get; set; }
        public Nullable<int> WOAccessoryId { get; set; }
        public Nullable<int> RepairClassTypeId { get; set; }
        public Nullable<int> WOEnqCustFeedbackId { get; set; }
        public Nullable<int> CaseStatusId { get; set; }
        public string QueueName { get; set; }
        public string ProdModelIfOther { get; set; }
        public string ProdDescriptionIfOther { get; set; }
        public string CustomerSecondaryName { get; set; }
        public Nullable<int> WOProofOfPurchaseId { get; set; }
        public Nullable<int> WOSnapsId { get; set; }
        public Nullable<int> RescheduleReasonId { get; set; }
        public Nullable<System.DateTime> RescheduleDate { get; set; }
        public string OrganizationName { get; set; }
    }
}
