//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraRegaAV.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrderEnquiry
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string AlternateMobileNo { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string CustomerGSTNo { get; set; }
        public string CustomerPANNo { get; set; }
        public int ProductModelId { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<int> ProductDescId { get; set; }
        public string ProductSerialNo { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
        public string WarrantyOrAMCNo { get; set; }
        public Nullable<int> PurchaseCountryId { get; set; }
        public Nullable<int> OSId { get; set; }
        public Nullable<int> IssueDescId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SourceChannelId { get; set; }
        public Nullable<int> EnquiryStatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IssueDesc { get; set; }
        public int ServiceAddressId { get; set; }
        public string ProdModelIfOther { get; set; }
        public string AttributeImagePath { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductMakeId { get; set; }
        public string ProdDescriptionIfOther { get; set; }
        public string OrganizationName { get; set; }
    }
}
