using OraRegaAV.Controllers.API;
using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace OraRegaAV.Controllers
{
    public class InvoiceAPIController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public InvoiceAPIController()
        {
            _response.IsSuccess = true;
        }

        [HttpPost]
        [Route("api/InvoiceAPI/SaveInvoice")]
        public async Task<Response> SaveInvoice(InvoiceRequest request)
        {
            try
            {
                //check work order status
                var vWorkOrder = db.tblWorkOrders.Where(x => x.Id == request.WorkOrderId && x.OrderStatusId == 5).FirstOrDefault();
                if (vWorkOrder == null)
                {
                    _response.IsSuccess = false;
                    _response.Message = "Work Order Status is not Closed.";
                    return _response;
                }

                var tbl = db.tblInvoices.Where(x => x.Id == request.Id).FirstOrDefault();
                if (tbl == null)
                {
                    tbl = new tblInvoice();

                    //get branch state short code
                    string vStateShortCode = "";
                    var vBranchStateId = db.tblBranches.Where(x => x.Id == vWorkOrder.BranchId).Select(x => x.StateId).FirstOrDefault();
                    if (vBranchStateId != null)
                    {
                        vStateShortCode = db.tblStates.Where(x => x.Id == vBranchStateId).Select(x => x.StateShortCode).FirstOrDefault();
                    }

                    tbl.InvoiceDate = request.InvoiceDate;
                    tbl.InvoiceNumber = Utilities.InvoiceNumberAutoGenerated(vStateShortCode);
                    tbl.WorkOrderId = request.WorkOrderId;

                    tbl.AmountBeforeTax = request.AmountBeforeTax;
                    tbl.CGSTPerct = request.CGSTPerct;
                    tbl.CGSTValue = request.CGSTValue;
                    tbl.SGSTPerct = request.SGSTPerct;
                    tbl.SGSTValue = request.SGSTValue;
                    tbl.IGSTPerct = request.IGSTPerct;
                    tbl.IGSTValue = request.IGSTValue;
                    tbl.TotalAmountWithGST = request.TotalAmountWithGST;
                    tbl.AmountPaidAfter = request.AmountPaidAfter;

                    tbl.CreatedBy = Utilities.GetUserID(ActionContext.Request);
                    tbl.CreatedDate = DateTime.Now;

                    db.tblInvoices.Add(tbl);
                    await db.SaveChangesAsync();

                    //foreach (var item in request.invoicePartDetails)
                    //{
                    //    tblInvoicePartDetail vItem = new tblInvoicePartDetail()
                    //    {
                    //        InvoiceId = tbl.Id,
                    //        PartId = item.PartId,
                    //        Qty = item.Qty,
                    //        Price = item.Price,
                    //        DiscPerct = item.DiscPerct,
                    //        DiscValue = item.DiscValue,
                    //        TotalAmount = item.TotalAmount,
                    //    };

                    //    db.tblInvoicePartDetails.Add(vItem);

                    //    await db.SaveChangesAsync();
                    //}

                    _response.IsSuccess = true;
                    _response.Message = "Invoice details saved successfully";
                }
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }
            return _response;
        }

        [HttpPost]
        [Route("api/InvoiceAPI/InvoiceList")]
        public Response InvoiceList(InvoiceSearchParameters parameters)
        {
            List<GetInvoiceList_Response> tblInvoiceList = new List<GetInvoiceList_Response>();

            try
            {
                var vTotal = new ObjectParameter("Total", typeof(int));
                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);

                var vInvoiceObjList = db.GetInvoiceList(parameters.CompanyId, parameters.BranchId, parameters.InvoiceNumber, parameters.WorkOrderNumber, parameters.SearchValue, parameters.PageSize, parameters.PageNo, vTotal, userId).ToList();

                foreach (var item in vInvoiceObjList)
                {
                    var vItemObj = new GetInvoiceList_Response()
                    {
                        Id = item.Id,
                        InvoiceDate = item.InvoiceDate,
                        InvoiceNumber = item.InvoiceNumber,
                        QuotationId = item.QuotationId,
                        QuotationNumber = item.QuotationNumber,
                        WorkOrderId = item.WorkOrderId,
                        WorkOrderNumber = item.WorkOrderNumber,
                        ProductSerialNumber = item.ProductSerialNumber,
                        BranchId = item.BranchId,
                        BranchName = item.BranchName,
                        BranchOfficeAddress = item.BranchOfficeAddress,
                        BranchGSTNumber = item.BranchGSTNumber,
                        StateCode = item.StateCode,
                        CustomerGstNumber = item.CustomerGstNumber,
                        ServiceAddressId = item.ServiceAddressId,
                        BillToAddress = item.BillToAddress,
                        CustomerName = item.CustomerName,
                        ContactPerson = item.ContactPerson,
                        CustomerEmail = item.CustomerEmail,
                        CustomerMobile = item.CustomerMobile,

                        AmountBeforeTax = item.AmountBeforeTax,
                        CGSTPerct = item.CGSTPerct,
                        CGSTValue = item.CGSTValue,
                        SGSTPerct = item.SGSTPerct,
                        SGSTValue = item.SGSTValue,
                        IGSTPerct = item.IGSTPerct,
                        IGSTValue = item.IGSTValue,
                        TotalAmountWithGST = item.TotalAmountWithGST,
                        AmountPaidAfter = item.AmountPaidAfter,
                        CreatedBy = item.CreatedBy,
                        CreatorName = item.CreatorName,
                    };

                    var vPartsList = db.tblQuotationPartDetails.Where(x => x.Id == item.QuotationId).ToList();
                    foreach (var itemWOPart in vPartsList)
                    {
                        string sPartNumber = "";
                        string sPartDescription = "";
                        string sHSNCode = "";

                        var vPartObj = db.tblPartDetails.Where(x => x.Id == itemWOPart.PartId).FirstOrDefault();
                        if (vPartObj != null)
                        {
                            var objHSN = db.tblHSNCodeGSTMappings.Where(x => x.Id == vPartObj.HSNCodeId).FirstOrDefault();
                            if (objHSN != null)
                            {
                                sHSNCode = objHSN.HSNCode;
                            }

                            sPartNumber = vPartObj.PartNumber;
                            sPartDescription = vPartObj.PartDescription;
                        }

                        vItemObj.PartList.Add(new InvoicePartDetails_Response
                        {
                            PartId = vPartObj.Id,
                            PartNumber = sPartNumber,
                            HSN_SAC = sHSNCode,
                            PartDescription = sPartDescription,
                            Qty = itemWOPart.Qty,
                            Price = itemWOPart.Price,
                            DiscPerct = itemWOPart.DiscPerct,
                            DiscValue = itemWOPart.DiscValue,
                            //TotalAmount = itemWOPart.a,
                        });
                    }

                    tblInvoiceList.Add(vItemObj);
                }

                _response.Data = tblInvoiceList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        [Route("api/InvoiceAPI/InvoiceDetailByInvoiceNumber")]
        public Response InvoiceDetailByInvoiceNumber(string InvoiceNumber)
        {
            List<GetInvoiceList_Response> tblInvoiceList = new List<GetInvoiceList_Response>();

            try
            {
                var vTotal = new ObjectParameter("Total", typeof(int));
                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);

                var vQuotationObjList = db.GetInvoiceList(0, 0, InvoiceNumber, string.Empty, string.Empty, 0, 0, vTotal, userId).ToList();

                foreach (var item in vQuotationObjList)
                {
                    var vItemObj = new GetInvoiceList_Response()
                    {
                        Id = item.Id,
                        InvoiceDate = item.InvoiceDate,
                        InvoiceNumber = item.InvoiceNumber,
                        QuotationId = item.QuotationId,
                        QuotationNumber = item.QuotationNumber,
                        WorkOrderId = item.WorkOrderId,
                        WorkOrderNumber = item.WorkOrderNumber,
                        ProductSerialNumber = item.ProductSerialNumber,
                        BranchId = item.BranchId,
                        BranchName = item.BranchName,
                        BranchOfficeAddress = item.BranchOfficeAddress,
                        BranchGSTNumber = item.BranchGSTNumber,
                        StateCode = item.StateCode,
                        CustomerGstNumber = item.CustomerGstNumber,
                        ServiceAddressId = item.ServiceAddressId,
                        BillToAddress = item.BillToAddress,
                        CustomerName = item.CustomerName,
                        ContactPerson = item.ContactPerson,
                        CustomerEmail = item.CustomerEmail,
                        CustomerMobile = item.CustomerMobile,

                        AmountBeforeTax = item.AmountBeforeTax,
                        CGSTPerct = item.CGSTPerct,
                        CGSTValue = item.CGSTValue,
                        SGSTPerct = item.SGSTPerct,
                        SGSTValue = item.SGSTValue,
                        IGSTPerct = item.IGSTPerct,
                        IGSTValue = item.IGSTValue,
                        TotalAmountWithGST = item.TotalAmountWithGST,
                        AmountPaidAfter = item.AmountPaidAfter,
                        CreatedBy = item.CreatedBy,
                        CreatorName = item.CreatorName,
                    };

                    //get service charge details
                    //var vServiceChargeDetailList = db.tblQuotationServiceChargeDetailses.Where(x => x.Id == item.QuotationId).ToList();
                    //foreach (var itemServiceCharge in vServiceChargeDetailList)
                    //{
                    //    string sPartNumber = "";
                    //    string sHSNCode = "";

                    //    var objHSN = db.tblHSNCodeGSTMappings.Where(x => x.Id == itemServiceCharge.HSNCodeId).FirstOrDefault();
                    //    if (objHSN != null)
                    //    {
                    //        sHSNCode = objHSN.HSNCode;
                    //    }

                    //    vItemObj.PartList.Add(new InvoicePartDetails_Response
                    //    {
                    //        PartId = 0,
                    //        PartNumber = sPartNumber,
                    //        HSN_SAC = sHSNCode,
                    //        PartDescription = itemServiceCharge.Description,
                    //        Qty = itemServiceCharge.Qty,
                    //        Price = itemServiceCharge.Price,
                    //        DiscPerct = itemServiceCharge.DiscPerct,
                    //        DiscValue = itemServiceCharge.DiscValue,
                    //        //TotalAmount = itemWOPart.TotalAmount,
                    //    });
                    //}

                    //get part details
                    var vPartsList = db.tblQuotationPartDetails.Where(x => x.Id == item.QuotationId).ToList();
                    foreach (var itemWOPart in vPartsList)
                    {
                        string sPartNumber = "";
                        string sPartDescription = "";
                        string sHSNCode = "";

                        var vPartObj = db.tblPartDetails.Where(x => x.Id == itemWOPart.PartId).FirstOrDefault();
                        if (vPartObj != null)
                        {
                            var objHSN = db.tblHSNCodeGSTMappings.Where(x => x.Id == vPartObj.HSNCodeId).FirstOrDefault();
                            if (objHSN != null)
                            {
                                sHSNCode = objHSN.HSNCode;
                            }

                            sPartNumber = vPartObj.PartNumber;
                            sPartDescription = vPartObj.PartDescription;
                        }

                        vItemObj.PartList.Add(new InvoicePartDetails_Response
                        {
                            PartId = vPartObj.Id,
                            PartNumber = sPartNumber,
                            HSN_SAC = sHSNCode,
                            PartDescription = sPartDescription,
                            Qty = itemWOPart.Qty,
                            Price = itemWOPart.Price,
                            DiscPerct = itemWOPart.DiscPerct,
                            DiscValue = itemWOPart.DiscValue,
                            //TotalAmount = itemWOPart.TotalAmount,
                        });
                    }

                    tblInvoiceList.Add(vItemObj);
                }

                _response.Data = tblInvoiceList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }
    }
}