using OraRegaAV.Controllers.API;
using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace OraRegaAV.Controllers
{
    public class InvoiceAPIController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public InvoiceAPIController()
        {
            _response.IsSuccess = true;
        }

        //[HttpPost]
        //[Route("api/InvoiceAPI/SaveInvoice")]
        //public async Task<Response> SaveInvoice(InvoiceRequest request)
        //{
        //    try
        //    {
        //        var tbl = db.tblInvoices.Where(x => x.Id == request.Id).FirstOrDefault();
        //        if (tbl == null)
        //        {
        //            tbl = new tblInvoice();

        //            tbl.InvoiceDate = request.InvoiceDate;
        //            tbl.InvoiceNumber = Utilities.QuotationNumberAutoGenerated();
        //            tbl.WorkOrderId = request.WorkOrderId;

        //            tbl.AmountBeforeTax = request.AmountBeforeTax;
        //            tbl.CGSTPerct = request.CGSTPerct;
        //            tbl.CGSTValue = request.CGSTValue;
        //            tbl.SGSTPerct = request.SGSTPerct;
        //            tbl.SGSTValue = request.SGSTValue;
        //            tbl.IGSTPerct = request.IGSTPerct;
        //            tbl.IGSTValue = request.IGSTValue;
        //            tbl.TotalAmountWithGST = request.TotalAmountWithGST;
        //            tbl.AmountPaidAfter = request.AmountPaidAfter;

        //            tbl.CreatedBy = Utilities.GetUserID(ActionContext.Request);
        //            tbl.CreatedDate = DateTime.Now;

        //            db.tblInvoices.Add(tbl);
        //            await db.SaveChangesAsync();

        //            foreach (var item in request.invoicePartDetails)
        //            {
        //                tblInvoicePartDetail vItem = new tblInvoicePartDetail()
        //                {
        //                    InvoiceId = tbl.Id,
        //                    PartId = item.PartId,
        //                    Qty = item.Qty,
        //                    Price = item.Price,
        //                    DiscPerct = item.DiscPerct,
        //                    DiscValue = item.DiscValue,
        //                    TotalAmount = item.TotalAmount,
        //                };

        //                db.tblInvoicePartDetails.Add(vItem);

        //                await db.SaveChangesAsync();
        //            }

        //            _response.IsSuccess = true;
        //            _response.Message = "Invoice details saved successfully";
        //        }
        //        else
        //        {
        //            tbl.InvoiceDate = request.InvoiceDate;
        //            tbl.WorkOrderId = request.WorkOrderId;

        //            tbl.AmountBeforeTax = request.AmountBeforeTax;
        //            tbl.CGSTPerct = request.CGSTPerct;
        //            tbl.CGSTValue = request.CGSTValue;
        //            tbl.SGSTPerct = request.SGSTPerct;
        //            tbl.SGSTValue = request.SGSTValue;
        //            tbl.IGSTPerct = request.IGSTPerct;
        //            tbl.IGSTValue = request.IGSTValue;
        //            tbl.TotalAmountWithGST = request.TotalAmountWithGST;
        //            tbl.AmountPaidAfter = request.AmountPaidAfter;

        //            tbl.ModifiedBy = Utilities.GetUserID(ActionContext.Request);
        //            tbl.ModifiedDate = DateTime.Now;

        //            await db.SaveChangesAsync();

        //            //delete prev invoice part details
        //            var vQuotationPartDetails = db.tblInvoicePartDetails.Where(x => x.InvoiceId == tbl.Id).ToList();
        //            foreach (var item in vQuotationPartDetails)
        //            {
        //                db.tblInvoicePartDetails.Remove(item);
        //                await db.SaveChangesAsync();
        //            }

        //            foreach (var item in request.invoicePartDetails)
        //            {
        //                tblInvoicePartDetail vItem = new tblInvoicePartDetail()
        //                {
        //                    InvoiceId = tbl.Id,
        //                    PartId = item.PartId,
        //                    Qty = item.Qty,
        //                    Price = item.Price,
        //                    DiscPerct = item.DiscPerct,
        //                    DiscValue = item.DiscValue,
        //                    TotalAmount = item.TotalAmount,
        //                };

        //                db.tblInvoicePartDetails.Add(vItem);

        //                await db.SaveChangesAsync();
        //            }

        //            _response.IsSuccess = true;
        //            _response.Message = "Invoice details updated successfully";
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        _response.IsSuccess = false;
        //        _response.Message = ValidationConstant.InternalServerError;
        //        LogWriter.WriteLog(ex);
        //    }
        //    return _response;
        //}

        //[HttpPost]
        //[Route("api/InvoiceAPI/InvoiceList")]
        //public Response InvoiceList(InvoiceSearchParameters parameters)
        //{
        //    List<GetInvoiceList_Response> tblInvoiceList = new List<GetInvoiceList_Response>();

        //    try
        //    {
        //        var vTotal = new ObjectParameter("Total", typeof(int));
        //        var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);

        //        var vInvoiceObjList = db.GetInvoiceList(parameters.CompanyId, parameters.BranchId, parameters.InvoiceNumber, parameters.WorkOrderNumber, parameters.SearchValue, parameters.PageSize, parameters.PageNo, vTotal, userId).ToList();

        //        foreach (var item in vInvoiceObjList)
        //        {
        //            var vItemObj = new GetInvoiceList_Response()
        //            {
        //                Id = item.Id,
        //                InvoiceDate = item.InvoiceDate,
        //                InvoiceNumber = item.InvoiceNumber,
        //                WorkOrderId = item.WorkOrderId,
        //                WorkOrderNumber = item.WorkOrderNumber,
        //                CustomerGstNumber = item.CustomerGstNumber,
        //                ServiceAddressId = item.ServiceAddressId,
        //                BillToAddress = item.BillToAddress,
        //                DeliverToAddress = item.DeliverToAddress,
        //                CustomerName = item.CustomerName,
        //                ContactPerson = item.ContactPerson,
        //                CustomerEmail = item.CustomerEmail,
        //                CustomerMobile = item.CustomerMobile,
        //                BranchId = item.BranchId,
        //                BranchName = item.BranchName,
        //                BranchOfficeAddress = item.BranchOfficeAddress,
        //                BranchGSTNumber = item.BranchGSTNumber,
        //                ProductModelId = item.ProductModelId,
        //                ProductModel = item.ProductModel,
        //                ProdModelIfOther = item.ProdModelIfOther,
        //                ProductSerialNumber = item.ProductSerialNumber,
        //                ProductNumber = item.ProductNumber,
        //                ProductDescriptionId = item.ProductDescriptionId,
        //                ProductDescription = item.ProductDescription,
        //                ProdDescriptionIfOther = item.ProdDescriptionIfOther,
        //                PlaceOfSupply = item.PlaceOfSupply,
        //                StateCode = item.StateCode,
        //                AmountBeforeTax = item.AmountBeforeTax,
        //                CGSTPerct = item.CGSTPerct,
        //                CGSTValue = item.CGSTValue,
        //                SGSTPerct = item.SGSTPerct,
        //                SGSTValue = item.SGSTValue,
        //                IGSTPerct = item.IGSTPerct,
        //                IGSTValue = item.IGSTValue,
        //                TotalAmountWithGST = item.TotalAmountWithGST,
        //                AmountPaidAfter = item.AmountPaidAfter,
        //                CreatedBy = item.CreatedBy,
        //                CreatorName = item.CreatorName,
        //            };

        //            var vPartsList = db.tblInvoicePartDetails.Where(x => x.InvoiceId == item.Id).ToList();
        //            foreach (var itemWOPart in vPartsList)
        //            {
        //                string sPartName = "";
        //                string sPartNumber = "";
        //                string sUniqueNumber = "";
        //                string sPartDescription = "";
        //                string sSerialNumber = "";
        //                string sHSNCode = "";

        //                var vPartObj = db.tblPartDetails.Where(x => x.Id == itemWOPart.PartId).FirstOrDefault();
        //                if (vPartObj != null)
        //                {
        //                    //var vPartStatusObj = db.tblPartDescriptions.Where(x => x.Id == itemWOPart.PartStatusId).FirstOrDefault();
        //                    //if (vPartStatusObj != null)
        //                    //{
        //                    //    sPartStatus = vPartStatusObj.PartDescriptionName;
        //                    //}

        //                    var objHSN = db.tblHSNCodeGSTMappings.Where(x => x.Id == vPartObj.HSNCodeId).FirstOrDefault();
        //                    if (objHSN != null)
        //                    {
        //                        sHSNCode = objHSN.HSNCode;
        //                    }

        //                    sPartName = vPartObj.PartName;
        //                    sPartNumber = vPartObj.PartNumber;
        //                    sUniqueNumber = vPartObj.UniqueCode;
        //                    sPartDescription = vPartObj.PartDescription;
        //                    sSerialNumber = vPartObj.CTSerialNo;
        //                }

        //                vItemObj.PartList.Add(new InvoicePartDetails_Response
        //                {
        //                    PartId = vPartObj.Id,
        //                    PartNumber = sPartNumber,
        //                    HSN_SAC = sHSNCode,
        //                    PartDescription = sPartDescription,
        //                    Qty = itemWOPart.Qty,
        //                    Price = itemWOPart.Price,
        //                    DiscPerct = itemWOPart.DiscPerct,
        //                    DiscValue = itemWOPart.DiscValue,
        //                    TotalAmount = itemWOPart.TotalAmount,
        //                });
        //            }

        //            tblInvoiceList.Add(vItemObj);
        //        }

        //        _response.Data = tblInvoiceList;
        //    }
        //    catch (Exception ex)
        //    {
        //        _response.IsSuccess = false;
        //        _response.Message = ValidationConstant.InternalServerError;
        //        LogWriter.WriteLog(ex);
        //    }

        //    return _response;
        //}

        //[HttpPost]
        //[Route("api/InvoiceAPI/InvoiceDetailByInvoiceNumber")]
        //public Response InvoiceDetailByInvoiceNumber(string InvoiceNumber)
        //{
        //    List<GetQuotationList_Response> tblQuotationList = new List<GetQuotationList_Response>();

        //    try
        //    {
        //        var vTotal = new ObjectParameter("Total", typeof(int));
        //        var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);

        //        var vQuotationObjList = db.GetQuotationList(0, 0, InvoiceNumber, string.Empty, string.Empty, 0, 0, vTotal, userId).ToList();

        //        foreach (var item in vQuotationObjList)
        //        {
        //            var vItemObj = new GetQuotationList_Response()
        //            {
        //                Id = item.Id,
        //                QuoteDate = item.QuoteDate,
        //                QuotationNumber = item.QuotationNumber,
        //                WorkOrderId = item.WorkOrderId,
        //                WorkOrderNumber = item.WorkOrderNumber,
        //                CustomerGstNumber = item.CustomerGstNumber,
        //                ServiceAddressId = item.ServiceAddressId,
        //                BillToAddress = item.BillToAddress,
        //                DeliverToAddress = item.DeliverToAddress,
        //                CustomerName = item.CustomerName,
        //                ContactPerson = item.ContactPerson,
        //                CustomerEmail = item.CustomerEmail,
        //                CustomerMobile = item.CustomerMobile,
        //                BranchId = item.BranchId,
        //                BranchName = item.BranchName,
        //                BranchOfficeAddress = item.BranchOfficeAddress,
        //                BranchGSTNumber = item.BranchGSTNumber,
        //                ProductModelId = item.ProductModelId,
        //                ProductModel = item.ProductModel,
        //                ProdModelIfOther = item.ProdModelIfOther,
        //                ProductSerialNumber = item.ProductSerialNumber,
        //                ProductNumber = item.ProductNumber,
        //                ProductDescriptionId = item.ProductDescriptionId,
        //                ProductDescription = item.ProductDescription,
        //                ProdDescriptionIfOther = item.ProdDescriptionIfOther,
        //                PlaceOfSupply = item.PlaceOfSupply,
        //                StateCode = item.StateCode,
        //                AmountBeforeTax = item.AmountBeforeTax,
        //                TotalCGSTValue = item.TotalCGSTValue,
        //                TotalSGSTValue = item.TotalSGSTValue,
        //                GrossAmount = item.GrossAmount,
        //                AdvanceReceived = item.AdvanceReceived,
        //                AmountPaid = item.AmountPaid,
        //                CreatedBy = item.CreatedBy,
        //                CreatorName = item.CreatorName,
        //            };

        //            var vPartsList = db.tblQuotationPartDetails.Where(x => x.QuotationId == item.Id).ToList();
        //            foreach (var itemWOPart in vPartsList)
        //            {
        //                string sPartName = "";
        //                string sPartNumber = "";
        //                string sUniqueNumber = "";
        //                string sPartDescription = "";
        //                string sSerialNumber = "";
        //                string sPartStatus = "";
        //                string sHSNCode = "";

        //                var vPartObj = db.tblPartDetails.Where(x => x.Id == itemWOPart.PartId).FirstOrDefault();
        //                if (vPartObj != null)
        //                {
        //                    //var vPartStatusObj = db.tblPartDescriptions.Where(x => x.Id == itemWOPart.PartStatusId).FirstOrDefault();
        //                    //if (vPartStatusObj != null)
        //                    //{
        //                    //    sPartStatus = vPartStatusObj.PartDescriptionName;
        //                    //}

        //                    var objHSN = db.tblHSNCodeGSTMappings.Where(x => x.Id == vPartObj.HSNCodeId).FirstOrDefault();
        //                    if (objHSN != null)
        //                    {
        //                        sHSNCode = objHSN.HSNCode;
        //                    }

        //                    sPartName = vPartObj.PartName;
        //                    sPartNumber = vPartObj.PartNumber;
        //                    sUniqueNumber = vPartObj.UniqueCode;
        //                    sPartDescription = vPartObj.PartDescription;
        //                    sSerialNumber = vPartObj.CTSerialNo;
        //                }

        //                vItemObj.PartList.Add(new QuotationPartDetails_Response
        //                {
        //                    PartId = vPartObj.Id,
        //                    PartNumber = sPartNumber,
        //                    HSN_SAC = sHSNCode,
        //                    PartDescription = sPartDescription,
        //                    Qty = itemWOPart.Qty,
        //                    Price = itemWOPart.Price,
        //                    DiscPerct = itemWOPart.DiscPerct,
        //                    DiscValue = itemWOPart.DiscValue,
        //                    CGSTPerct = itemWOPart.CGSTPerct,
        //                    CGSTValue = itemWOPart.CGSTValue,
        //                    SGSTPerct = itemWOPart.SGSTPerct,
        //                    SGSTValue = itemWOPart.SGSTValue,
        //                    IGSTPerct = itemWOPart.IGSTPerct,
        //                    IGSTValue = itemWOPart.IGSTValue
        //                });
        //            }

        //            tblQuotationList.Add(vItemObj);
        //        }

        //        _response.Data = tblQuotationList;
        //    }
        //    catch (Exception ex)
        //    {
        //        _response.IsSuccess = false;
        //        _response.Message = ValidationConstant.InternalServerError;
        //        LogWriter.WriteLog(ex);
        //    }

        //    return _response;
        //}
    }
}