using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;

namespace OraRegaAV.Controllers.API
{
    public class PartDetailAPIController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();
        public PartDetailAPIController()
        {
            _response.IsSuccess = true;
        }

        [HttpPost]
        public async Task<Response> SavePartDetail(tblPartDetail objtblPartDetail)
        {
            tblPartDetail tblPartDetail;

            try
            {
                //var ucode = Utilities.PartDetails_UniqueCodeAutoGenerated();
                tblPartDetail = db.tblPartDetails.Where(record => record.Id == objtblPartDetail.Id).FirstOrDefault();

                if (tblPartDetail == null)
                {
                    if (objtblPartDetail.Quantity == 0)
                    {
                        tblPartDetail = new tblPartDetail();
                        //tblPartDetail.UniqueCode = objtblPartDetail.UniqueCode;
                        tblPartDetail.UniqueCode = Utilities.PartDetails_UniqueCodeAutoGenerated();
                        tblPartDetail.PartNumber = objtblPartDetail.PartNumber;
                        tblPartDetail.PartName = objtblPartDetail.PartName;
                        tblPartDetail.PartDescription = objtblPartDetail.PartDescription;
                        tblPartDetail.HSNCodeId = objtblPartDetail.HSNCodeId;
                        tblPartDetail.CTSerialNo = objtblPartDetail.CTSerialNo;
                        tblPartDetail.PartStatusId = objtblPartDetail.PartStatusId;
                        tblPartDetail.SalePrice = objtblPartDetail.SalePrice;
                        tblPartDetail.IsActive = objtblPartDetail.IsActive;
                        tblPartDetail.CompanyId = objtblPartDetail.CompanyId;
                        tblPartDetail.BranchId = objtblPartDetail.BranchId;
                        tblPartDetail.ReceiveFrom = objtblPartDetail.ReceiveFrom;
                        tblPartDetail.ReceiveDate = objtblPartDetail.ReceiveDate;
                        tblPartDetail.DocketNo = objtblPartDetail.DocketNo;
                        tblPartDetail.PurchasePrice = objtblPartDetail.PurchasePrice;
                        tblPartDetail.VendorId = objtblPartDetail.VendorId;
                        tblPartDetail.StockPartStatusId = objtblPartDetail.StockPartStatusId;
                        tblPartDetail.Quantity = objtblPartDetail.Quantity;
                        tblPartDetail.CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                        tblPartDetail.CreatedDate = DateTime.Now;

                        db.tblPartDetails.AddOrUpdate(tblPartDetail);

                        await db.SaveChangesAsync();
                    }
                    if (objtblPartDetail.Quantity > 0)
                    {
                        for (int i = 0; i < objtblPartDetail.Quantity; i++)
                        {
                            tblPartDetail = new tblPartDetail();
                            //tblPartDetail.UniqueCode = objtblPartDetail.UniqueCode;
                            tblPartDetail.UniqueCode = Utilities.PartDetails_UniqueCodeAutoGenerated();
                            tblPartDetail.PartNumber = objtblPartDetail.PartNumber;
                            tblPartDetail.PartName = objtblPartDetail.PartName;
                            tblPartDetail.PartDescription = objtblPartDetail.PartDescription;
                            tblPartDetail.HSNCodeId = objtblPartDetail.HSNCodeId;
                            tblPartDetail.CTSerialNo = objtblPartDetail.CTSerialNo;
                            tblPartDetail.PartStatusId = objtblPartDetail.PartStatusId;
                            tblPartDetail.SalePrice = objtblPartDetail.SalePrice;
                            tblPartDetail.IsActive = objtblPartDetail.IsActive;
                            tblPartDetail.CompanyId = objtblPartDetail.CompanyId;
                            tblPartDetail.BranchId = objtblPartDetail.BranchId;
                            tblPartDetail.ReceiveFrom = objtblPartDetail.ReceiveFrom;
                            tblPartDetail.ReceiveDate = objtblPartDetail.ReceiveDate;
                            tblPartDetail.DocketNo = objtblPartDetail.DocketNo;
                            tblPartDetail.PurchasePrice = objtblPartDetail.PurchasePrice;
                            tblPartDetail.VendorId = objtblPartDetail.VendorId;
                            tblPartDetail.StockPartStatusId = objtblPartDetail.StockPartStatusId;
                            tblPartDetail.Quantity = 1;//objtblPartDetail.Quantity;
                            tblPartDetail.CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                            tblPartDetail.CreatedDate = DateTime.Now;

                            db.tblPartDetails.AddOrUpdate(tblPartDetail);

                            await db.SaveChangesAsync();
                        }
                    }

                    _response.Message = "Part Details added successfully";
                }
                else
                {
                    //tblPartDetail.UniqueCode = objtblPartDetail.UniqueCode;
                    tblPartDetail.PartNumber = objtblPartDetail.PartNumber;
                    tblPartDetail.PartName = objtblPartDetail.PartName;
                    tblPartDetail.PartDescription = objtblPartDetail.PartDescription;
                    tblPartDetail.HSNCodeId = objtblPartDetail.HSNCodeId;
                    tblPartDetail.CTSerialNo = objtblPartDetail.CTSerialNo;
                    tblPartDetail.PartStatusId = objtblPartDetail.PartStatusId;
                    tblPartDetail.SalePrice = objtblPartDetail.SalePrice;
                    tblPartDetail.IsActive = objtblPartDetail.IsActive;
                    tblPartDetail.CompanyId = objtblPartDetail.CompanyId;
                    tblPartDetail.BranchId = objtblPartDetail.BranchId;
                    tblPartDetail.ReceiveFrom = objtblPartDetail.ReceiveFrom;
                    tblPartDetail.ReceiveDate = objtblPartDetail.ReceiveDate;
                    tblPartDetail.DocketNo = objtblPartDetail.DocketNo;
                    tblPartDetail.PurchasePrice = objtblPartDetail.PurchasePrice;
                    tblPartDetail.VendorId = objtblPartDetail.VendorId;
                    tblPartDetail.StockPartStatusId = objtblPartDetail.StockPartStatusId;
                    tblPartDetail.Quantity = objtblPartDetail.Quantity;
                    tblPartDetail.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                    tblPartDetail.ModifiedDate = DateTime.Now;
                    _response.Message = "Part Details updated successfully";

                    db.tblPartDetails.AddOrUpdate(tblPartDetail);

                    await db.SaveChangesAsync();
                }


                if (objtblPartDetail.StockEntryId > 0)
                {
                    var objSAPMapping = await db.tblStockAndPartMappings.Where(x => x.StockEntryId == objtblPartDetail.StockEntryId && x.PartDetailId == tblPartDetail.Id).FirstOrDefaultAsync();
                    if (objSAPMapping == null)
                    {
                        tblStockAndPartMapping objTblStockAndPartMapping = new tblStockAndPartMapping()
                        {
                            CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0),
                            CreatedDate = DateTime.Now,
                            PartDetailId = tblPartDetail.Id,
                            StockEntryId = objtblPartDetail.StockEntryId
                        };
                        db.tblStockAndPartMappings.Add(objTblStockAndPartMapping);
                    }
                    else
                    {
                        objSAPMapping.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                        objSAPMapping.ModifiedDate = DateTime.Now;
                    }
                    await db.SaveChangesAsync();

                }
                _response.IsSuccess = true;

            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        public Response PartsList(PartDetailsSearchParameters parameters)
        {
            _response = RetrievePartsList(parameters.Id, parameters.CompanyId, parameters.BranchId, parameters.SearchValue.SanitizeValue(), parameters.UserId, parameters.PageSize, parameters.PageNo);
            return _response;
        }

        [HttpPost]
        public Response PartDetailsById([FromBody] int Id)
        {
            _response = RetrievePartsList(Id, 0, 0, "", 0, 0, 0);
            return _response;
        }

        private Response RetrievePartsList(int Id = 0, int CompanyId = 0, int BranchId = 0, string SearchValue = "", int UserId = 0, int PageSize = 0, int PageNo = 0)
        {
            List<GetPartDetailList_Result> tblPartDetailList;

            try
            {
                var vTotal = new ObjectParameter("Total", typeof(int));
                tblPartDetailList = db.GetPartDetailList(Id, CompanyId, BranchId, SearchValue, UserId, PageSize, PageNo, vTotal).ToList();

                _response.TotalCount = Convert.ToInt32(vTotal.Value);
                _response.Data = tblPartDetailList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }
    }
}
