using OraRegaAV.Controllers.API;
using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OraRegaAV.Controllers
{
    public class QuotationAPIController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public QuotationAPIController()
        {
            _response.IsSuccess = true;
        }

        [HttpPost]
        [Route("api/QuotationAPI/SaveQuotation")]
        public async Task<Response> SaveQuotation(QuotationRequest request)
        {
            try
            {
                var tbl = db.tblQuotations.Where(x => x.Id == request.Id).FirstOrDefault();
                if (tbl == null)
                {
                    tbl = new tblQuotation();

                    tbl.QuoteDate = request.QuoteDate;
                    tbl.QuotationNumber = Utilities.QuotationNumberAutoGenerated();
                    tbl.WorkOrderId = request.WorkOrderId;

                    tbl.AmountBeforeTax = request.AmountBeforeTax;
                    tbl.TotalCGSTValue = request.TotalCGSTValue;
                    tbl.TotalSGSTValue = request.TotalSGSTValue;
                    tbl.GrossAmount = request.GrossAmount;
                    tbl.AdvanceReceived = request.AdvanceReceived;
                    tbl.AmountPaid = request.AmountPaid;

                    tbl.CreatedBy = Utilities.GetUserID(ActionContext.Request);
                    tbl.CreatedDate = DateTime.Now;

                    db.tblQuotations.Add(tbl);
                    await db.SaveChangesAsync();

                    foreach (var item in request.quotationPartDetails)
                    {
                        tblQuotationPartDetail vItem = new tblQuotationPartDetail()
                        {
                            QuotationId = tbl.Id,
                            PartId = item.PartId,
                            Qty = item.Qty,
                            Price = item.Price,
                            DiscPerct = item.DiscPerct,
                            DiscValue = item.DiscValue,
                            CGSTPerct = item.CGSTPerct,
                            CGSTValue = item.CGSTValue,
                            SGSTPerct = item.SGSTPerct,
                            SGSTValue = item.SGSTValue,
                            IGSTPerct = item.IGSTPerct,
                            IGSTValue = item.IGSTValue,
                        };

                        db.tblQuotationPartDetails.Add(vItem);

                        await db.SaveChangesAsync();
                    }

                    _response.IsSuccess = true;
                    _response.Message = "Quotation details saved successfully";
                }
                else
                {
                    tbl.QuoteDate = request.QuoteDate;
                    tbl.WorkOrderId = request.WorkOrderId;

                    tbl.AmountBeforeTax = request.AmountBeforeTax;
                    tbl.TotalCGSTValue = request.TotalCGSTValue;
                    tbl.TotalSGSTValue = request.TotalSGSTValue;
                    tbl.GrossAmount = request.GrossAmount;
                    tbl.AdvanceReceived = request.AdvanceReceived;
                    tbl.AmountPaid = request.AmountPaid;

                    tbl.ModifiedBy = Utilities.GetUserID(ActionContext.Request);
                    tbl.ModifiedDate = DateTime.Now;

                    await db.SaveChangesAsync();

                    //delete prev quotation part details
                    var vQuotationPartDetails = db.tblQuotationPartDetails.Where(x => x.QuotationId == tbl.Id).ToList();
                    foreach(var item in vQuotationPartDetails)
                    {
                        db.tblQuotationPartDetails.Remove(item);
                        await db.SaveChangesAsync();
                    }

                    foreach (var item in request.quotationPartDetails)
                    {
                        tblQuotationPartDetail vItem = new tblQuotationPartDetail()
                        {
                            QuotationId = tbl.Id,
                            PartId = item.PartId,
                            Qty = item.Qty,
                            Price = item.Price,
                            DiscPerct = item.DiscPerct,
                            DiscValue = item.DiscValue,
                            CGSTPerct = item.CGSTPerct,
                            CGSTValue = item.CGSTValue,
                            SGSTPerct = item.SGSTPerct,
                            SGSTValue = item.SGSTValue,
                            IGSTPerct = item.IGSTPerct,
                            IGSTValue = item.IGSTValue,
                        };

                        db.tblQuotationPartDetails.Add(vItem);

                        await db.SaveChangesAsync();
                    }

                    _response.IsSuccess = true;
                    _response.Message = "Quotation details updated successfully";
                }
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }
            return _response;
        }
    }
}