using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Newtonsoft.Json;
using System.Web.UI.WebControls;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using OraRegaAV.Helpers;
using OraRegaAV.Models.Constants;
using Microsoft.AspNetCore.Mvc;
using OraRegaAV.DBEntity;
using OraRegaAV.Models;

namespace OraRegaAV.Controllers.API 
{
    public class RequestForAdvanceController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public RequestForAdvanceController()
        {
            _response.IsSuccess = true;
        }


        [HttpPost]
        [Route("api/RequestForAdvance/SaveRequestForAdvance")]
        public async Task<Response> SaveRequestForAdvance(RequestForAdvanceViewModel parameters)
        {
            tblRequestForAdvance tblRequestForAdvance;

            try
            {
                tblRequestForAdvance = db.tblRequestForAdvances.Where(record => record.Id == parameters.Id).FirstOrDefault();

                if (tblRequestForAdvance == null)
                {
                    tblRequestForAdvance = new tblRequestForAdvance()
                    {
                        ClaimId = Utilities.RequestForAdvanceClaimNumberAutoGenerated(),
                        EmployeeId = parameters.EmployeeId,
                        Date = parameters.Date,
                        Amount = parameters.Amount,
                        ClaimReason = parameters.ClaimReason,
                        AdvanceStatusId = 1,
                        CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0),
                        CreatedDate = DateTime.Now
                    };
                    _response.Message = "Advance added successfully";
                }
                else
                {
                    if (parameters.AdvanceStatusId == 0)  // Pending
                    {
                        tblRequestForAdvance.Date = parameters.Date;
                        tblRequestForAdvance.Amount = parameters.Amount;
                        tblRequestForAdvance.ClaimReason = parameters.ClaimReason;

                        tblRequestForAdvance.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                        tblRequestForAdvance.ModifiedDate = DateTime.Now;

                        _response.Message = "Advance updated successfully";
                    }

                    if (parameters.AdvanceStatusId == 2) // Approve
                    {
                        var vrequestForAdvance = db.tblRequestForAdvances.Where(record => record.EmployeeId == parameters.EmployeeId && record.AdvanceStatusId == 2).FirstOrDefault();
                        if (vrequestForAdvance != null)
                        {
                            var vtblClaimSettlement = db.tblClaimSettlements.Where(record => record.EmployeeId == parameters.EmployeeId && record.ClaimId == vrequestForAdvance.ClaimId && record.IsActive == true).FirstOrDefault();
                            if (vtblClaimSettlement == null)
                            {
                                _response.Message = "Sorry! you can't approve this because you have a advance of this Claim id " + vrequestForAdvance.ClaimId + " is still pending for sattlement";
                            }
                            else // if sattlement is done
                            {
                                tblRequestForAdvance.AdvanceStatusId = parameters.AdvanceStatusId;

                                tblRequestForAdvance.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                                tblRequestForAdvance.ModifiedDate = DateTime.Now;

                                _response.Message = "Advance updated successfully";
                            }
                        }
                        else // if sattlement is done
                        {
                            tblRequestForAdvance.AdvanceStatusId = parameters.AdvanceStatusId;

                            tblRequestForAdvance.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                            tblRequestForAdvance.ModifiedDate = DateTime.Now;

                            _response.Message = "Advance updated successfully";
                        }
                    }

                    if (parameters.AdvanceStatusId == 3) // Reject
                    {
                        tblRequestForAdvance.AdvanceStatusId = parameters.AdvanceStatusId;

                        tblRequestForAdvance.ModifiedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                        tblRequestForAdvance.ModifiedDate = DateTime.Now;

                        _response.Message = "Advance updated successfully";
                    }
                }

                db.tblRequestForAdvances.AddOrUpdate(tblRequestForAdvance);
                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        public Response RequestForAdvanceList(RequestForAdvanceListViewModel parameters)
        {
            try
            {
                List<GetRequestForAdvanceList_Result> advanceList = db.GetRequestForAdvanceList(parameters.EmployeeId, parameters.ClaimId, parameters.AdvanceStatusId).ToList();

                _response.Data = advanceList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        public Response RequestForAdvanceDetails(int AdvanceId)
        {
            try
            {
                var advanceObj = db.GetRequestForAdvanceList(0, "", 0).Where(x => x.Id == AdvanceId).FirstOrDefault();

                _response.Data = advanceObj;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }
    }
}
