using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Mvc;
using OraRegaAV.Controllers.API;
using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;

namespace OraRegaAV.Controllers
{
    public class SalesOrderController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public SalesOrderController()
        {
            _response.IsSuccess = true;
        }

        public async Task<Response> SaveSalesOrderDetails(tblSalesOrder parameters)
        {
            tblSalesOrder tbl;
            //tblSOCustomerComment tblComment;
            tblSalesOrderProduct tblSOProd;
            List<tblSalesOrderProduct> prodToBeDelete = new List<tblSalesOrderProduct>();
            List<int> foundsopID = new List<int>();
            int loggedInUserId;

            try
            {
                loggedInUserId = Utilities.GetUserID(ActionContext.Request);
                tbl = await db.tblSalesOrders.Where(x => x.Id == parameters.Id).FirstOrDefaultAsync();

                //Save or Update Sales Order Details
                if (tbl == null)
                {
                    tbl = new tblSalesOrder();

                    tbl.SalesOrderNumber = Utilities.SalesOrderNumberAutoGenerated();
                    tbl.TicketLogDate = DateTime.Now;

                    tbl.CompanyId = parameters.CompanyId;
                    tbl.BranchId = parameters.BranchId;
                    tbl.CustomerId = parameters.CustomerId;

                    tbl.AlternateNumber = parameters.AlternateNumber;
                    tbl.GstNumber = parameters.GstNumber;

                    tbl.CustomerAddressId = parameters.CustomerAddressId;
                    tbl.PaymentTermId = parameters.PaymentTermId;
                    tbl.IssueDescId = parameters.IssueDescId;
                    tbl.SalesOrderStatusId = parameters.SalesOrderStatusId;
                    tbl.Remark = parameters.Remark;
                    tbl.CustomerComment = parameters.CustomerComment;

                    tbl.CreatedBy = loggedInUserId;
                    tbl.CreatedDate = DateTime.Now;

                    db.tblSalesOrders.Add(tbl);

                    await db.SaveChangesAsync();

                    _response.Message = "Sales Order created successfully";
                    _response.Data = new { SalesOrderNumber = tbl.SalesOrderNumber, TicketLogDate = tbl.TicketLogDate };
                }
                else
                {
                    tbl.CompanyId = parameters.CompanyId;
                    tbl.BranchId = parameters.BranchId;
                    tbl.CustomerId = parameters.CustomerId;

                    tbl.AlternateNumber = parameters.AlternateNumber;
                    tbl.GstNumber = parameters.GstNumber;

                    tbl.CustomerAddressId = parameters.CustomerAddressId;
                    tbl.PaymentTermId = parameters.PaymentTermId;
                    tbl.IssueDescId = parameters.IssueDescId;
                    tbl.SalesOrderStatusId = parameters.SalesOrderStatusId;
                    tbl.Remark = parameters.Remark;
                    tbl.CustomerComment = parameters.CustomerComment;

                    tbl.ModifiedBy = loggedInUserId;
                    tbl.ModifiedDate = DateTime.Now;

                    _response.Message = "Sales Order updated successfully";
                }

                //Save or Update Comments
                //await db.tblSOCustomerComments.Where(c => c.SalesOrderId == tbl.Id).ForEachAsync(c =>
                //{
                //    c.IsDeleted = true;
                //});

                //foreach (string comment in parameters.CustomerComments)
                //{
                //    if (!string.IsNullOrEmpty(comment))
                //    {
                //        tblComment = new tblSOCustomerComment();
                //        tblComment.SalesOrderId = tbl.Id;
                //        tblComment.CustomerComment = comment;
                //        tblComment.IsDeleted = false;
                //        tblComment.CreatedBy = loggedInUserId;
                //        tblComment.CreatedDate = DateTime.Now;
                //        db.tblSOCustomerComments.Add(tblComment);
                //    }
                //}

                //Save or Update Product Details
                foreach (tblSalesOrderProduct prod in parameters.SalesOrderProducts)
                {
                    tblSOProd = prod.Id == 0 ? null : await db.tblSalesOrderProducts
                        .Where(record => record.SalesOrderId == tbl.Id && record.Id == prod.Id)
                        .FirstOrDefaultAsync();

                    if (tblSOProd == null)
                    {
                        tblSOProd = new tblSalesOrderProduct();
                        tblSOProd.SalesOrderId = tbl.Id;
                        tblSOProd.ProductTypeId = prod.ProductTypeId;
                        tblSOProd.ProductMakeId = prod.ProductMakeId;
                        tblSOProd.ProductModelId = prod.ProductModelId;
                        tblSOProd.ProductModelIfOther = prod.ProductModelIfOther;
                        tblSOProd.ProdDescriptionId = prod.ProdDescriptionId;
                        tblSOProd.ProductDescriptionIfOther = prod.ProductDescriptionIfOther;
                        tblSOProd.ProductConditionId = prod.ProductConditionId;
                        tblSOProd.ProductSerialNo = prod.ProductSerialNo;
                        tblSOProd.Quantity = prod.Quantity;
                        tblSOProd.Price = prod.Price;
                        tblSOProd.Comment = prod.Comment;
                        tblSOProd.IsDeleted = false;
                        tblSOProd.CreatedBy = loggedInUserId;
                        tblSOProd.CreatedDate = DateTime.Now;

                        db.tblSalesOrderProducts.Add(tblSOProd);
                    }
                    else
                    {
                        tblSOProd.ProductTypeId = prod.ProductTypeId;
                        tblSOProd.ProductMakeId = prod.ProductMakeId;
                        tblSOProd.ProductModelId = prod.ProductModelId;
                        tblSOProd.ProductModelIfOther = prod.ProductModelIfOther;
                        tblSOProd.ProdDescriptionId = prod.ProdDescriptionId;
                        tblSOProd.ProductDescriptionIfOther = prod.ProductDescriptionIfOther;
                        tblSOProd.ProductConditionId = prod.ProductConditionId;
                        tblSOProd.ProductSerialNo = prod.ProductSerialNo;
                        tblSOProd.Quantity = prod.Quantity;
                        tblSOProd.Price = prod.Price;
                        tblSOProd.Comment = prod.Comment;
                    }

                    await db.SaveChangesAsync();
                    foundsopID.Add(tblSOProd.Id);
                }

                //To delete removed products
                if (parameters.SalesOrderProducts.Count > 0)
                {
                    prodToBeDelete = await db.tblSalesOrderProducts.Where(record => record.SalesOrderId == tbl.Id
                        && !foundsopID.Contains(record.Id)).ToListAsync();
                }
                else
                {
                    prodToBeDelete = await db.tblSalesOrderProducts.Where(record => record.SalesOrderId == tbl.Id).ToListAsync();
                }

                foreach (tblSalesOrderProduct p in prodToBeDelete)
                {
                    await db.tblSalesOrderProducts.Where(prod => prod.Id == p.Id)
                        .ForEachAsync(temp =>
                        {
                            temp.IsDeleted = true;
                        });
                }

                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        public async Task<Response> RetrieveSalesOrdersList(SalesOrderListParameters parameters)
        {
            List<GetSalesOrdersList_Result> lstResult;
            int loggedInUserId = 0;

            try
            {
                //loggedInUserId = Utilities.GetUserID(ActionContext.Request);

                await Task.Run(() =>
                {
                    lstResult = db.GetSalesOrdersList(
                        parameters.CompanyId.SanitizeValue(),
                        parameters.BranchId.SanitizeValue(),
                        parameters.SalesOrderStatusId.SanitizeValue(),
                        loggedInUserId).ToList();

                    _response.Data = lstResult;
                });
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        public async Task<Response> RetrieveSalesOrderDetails(string salesOrderNo)
        {
            SalesOrderDetailsResult result;

            try
            {
                result = new SalesOrderDetailsResult();
                result.SODetails = new GetSalesOrderDetails_Result();
                //result.CommentsList = new List<GetSOCustomerCommentsList_Result>();
                result.ProductsList = new List<GetSalesOrderProductsList_Result>();

                await Task.Run(() =>
                {
                    result.SODetails = db.GetSalesOrderDetails(salesOrderNo).FirstOrDefault();

                    if (result.SODetails != null)
                    {
                        //result.CommentsList = db.GetSOCustomerCommentsList(result.SODetails.Id).ToList();
                        result.ProductsList = db.GetSalesOrderProductsList(result.SODetails.Id).ToList();
                    }
                });

                _response.Data = result;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }
    }
}