using Newtonsoft.Json;
using OraRegaAV.Controllers.API;
using OraRegaAV.DBEntity;
using OraRegaAV.Helpers;
using OraRegaAV.Models;
using OraRegaAV.Models.Constants;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace OraRegaAV.Controllers
{
    public class StockOutAPIController : ApiCustomBaseController
    {
        private readonly dbOraRegaEntities db = new dbOraRegaEntities();
        private Response _response = new Response();

        public StockOutAPIController()
        {
            _response.IsSuccess = true;
        }

        [HttpPost]
        [Route("api/StockOutAPIController/SaveStockTransferOut_DOA")]
        public async Task<Response> SaveStockTransferOut_DOA(StockTransferOutRequest parameters)
        {
            try
            {
                if (parameters.PartsDetail.Count > 0)
                {
                    var vtblStockTransferOuts = new tblStockOut_DAO()
                    {
                        ChallanNo = Utilities.StockOut_DOA_NumberAutoGenerated(),
                        ComapnyId = parameters.ComapnyId,
                        BranchFromId = parameters.BranchFromId,
                        BranchToId = parameters.BranchToId,
                        TransferDate = parameters.TransferDate,
                        NewDocketNo = parameters.NewDocketNo,
                        StockTransferOutDate = DateTime.Now,
                        CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0),
                        CreatedDate = DateTime.Now,
                    };

                    db.tblStockOut_DAO.AddOrUpdate(vtblStockTransferOuts);

                    await db.SaveChangesAsync();

                    foreach (var item in parameters.PartsDetail.ToList())
                    {
                        //if (!db.tblStockTransferPartDetails.Where(u => u.PartId == item.PartId).Any() && item.PartId > 0)
                        //{
                        var vtblStockTransferPartDetails = new tblStockOut_DAO_PartDetails()
                        {
                            StockOut_DAOId = vtblStockTransferOuts.Id,
                            DocketNo = item.DocketNo,
                            PartId = item.PartId
                        };
                        db.tblStockOut_DAO_PartDetails.AddOrUpdate(vtblStockTransferPartDetails);
                        //}
                    }

                    await db.SaveChangesAsync();

                    _response.Message = "Stock transfer successfully";
                }
                else
                {
                    _response.Message = "Stock not transfer successfully";
                }
            }
            catch
            {
                _response.IsSuccess = false;
                throw;
            }
            return _response;
        }

        [HttpPost]
        [Route("api/StockOutAPIController/GetStockOut_DAO_ChallanList")]
        public async Task<Response> GetStockOut_DAO_ChallanList(StockTransferOutDOA_DefectiveSearchParameters parameters)
        {
            try
            {
                List<GetStockOut_DAO_ChallanList_Result> advanceList = new List<GetStockOut_DAO_ChallanList_Result>();
                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                if (userId > 0)
                {
                    advanceList = db.GetStockOut_DAO_ChallanList(parameters.ComapnyId, parameters.BranchFromId, parameters.DockerNo, userId).ToList();
                }

                _response.Data = advanceList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        [Route("api/StockTransferAPI/GetStockOut_DAO_ByChallanNumber")]
        public Response GetStockOut_DAO_ByChallanNumber(string ChallanNo = "")
        {
            try
            {
                var stockTransferResponse = new StockOutResponse();

                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                if (userId > 0)
                {
                    var vStockTransferOutObj = db.GetStockOutDOAByChallanNumber(ChallanNo).FirstOrDefault();

                    if (vStockTransferOutObj != null)
                    {
                        var vCompaniesObj = db.tblCompanies.Where(x => x.Id == vStockTransferOutObj.ComapnyId).FirstOrDefault();

                        stockTransferResponse.Id = vStockTransferOutObj.Id;
                        stockTransferResponse.ChallanNo = vStockTransferOutObj.ChallanNo;
                        stockTransferResponse.CompanyId = vStockTransferOutObj.ComapnyId;
                        stockTransferResponse.CompanyName = vCompaniesObj != null ? vCompaniesObj.CompanyName : string.Empty;
                        stockTransferResponse.BranchFromId = vStockTransferOutObj.BranchFromId;
                        stockTransferResponse.BranchFromName = vStockTransferOutObj.BranchFromName;
                        stockTransferResponse.BranchToId = vStockTransferOutObj.BranchToId;
                        stockTransferResponse.BranchToName = vStockTransferOutObj.BranchToName;
                        stockTransferResponse.TransferDate = vStockTransferOutObj.TransferDate;
                        stockTransferResponse.NewDocketNo = vStockTransferOutObj.NewDocketNo;
                        stockTransferResponse.StockTransferOutDate = vStockTransferOutObj.StockTransferOutDate;

                        stockTransferResponse.CreatedBy = vStockTransferOutObj.CreatedBy;
                        stockTransferResponse.CreatorName = vStockTransferOutObj.CreatorName;
                        stockTransferResponse.CreatedDate = vStockTransferOutObj.CreatedDate;


                        var vStockTransferOutPartDetailList = db.tblStockOut_DAO_PartDetails.Where(x => x.StockOut_DAOId == vStockTransferOutObj.Id).ToList();

                        foreach (var item in vStockTransferOutPartDetailList)
                        {
                            var vPartDetailsObj = db.tblPartDetails.Where(x => x.Id == item.PartId).FirstOrDefault();

                            var vItemObj = new StockOutPartDetailResponse()
                            {
                                Id = item.Id,
                                StockTransferOutId = item.StockOut_DAOId,
                                DocketNo = item.DocketNo,
                                PartId = item.PartId,
                                PartName = vPartDetailsObj != null ? vPartDetailsObj.PartName : string.Empty,
                            };

                            stockTransferResponse.PartsDetail.Add(vItemObj);
                        }
                    }
                }

                _response.Data = stockTransferResponse;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        [Route("api/StockOutAPIController/SaveStockTransferOut_Defective")]
        public async Task<Response> SaveStockTransferOut_Defective(StockTransferOutRequest parameters)
        {
            try
            {
                if (parameters.PartsDetail.Count > 0)
                {
                    var vtblStockTransferOuts = new tblStockOut_Defective()
                    {
                        ChallanNo = Utilities.StockOut_Defective_NumberAutoGenerated(),
                        ComapnyId = parameters.ComapnyId,
                        BranchFromId = parameters.BranchFromId,
                        BranchToId = parameters.BranchToId,
                        TransferDate = parameters.TransferDate,
                        NewDocketNo = parameters.NewDocketNo,
                        StockTransferOutDate = DateTime.Now,
                        CreatedBy = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0),
                        CreatedDate = DateTime.Now,
                    };

                    db.tblStockOut_Defective.AddOrUpdate(vtblStockTransferOuts);

                    await db.SaveChangesAsync();

                    foreach (var item in parameters.PartsDetail.ToList())
                    {
                        //if (!db.tblStockTransferPartDetails.Where(u => u.PartId == item.PartId).Any() && item.PartId > 0)
                        //{
                        var vtblStockTransferPartDetails = new tblStockOut_Defective_PartDetails()
                        {
                            StockOut_DefectiveId = vtblStockTransferOuts.Id,
                            DocketNo = item.DocketNo,
                            PartId = item.PartId
                        };
                        db.tblStockOut_Defective_PartDetails.AddOrUpdate(vtblStockTransferPartDetails);
                        //}
                    }

                    await db.SaveChangesAsync();

                    _response.Message = "Stock transfer successfully";
                }
                else
                {
                    _response.Message = "Stock not transfer successfully";
                }
            }
            catch
            {
                _response.IsSuccess = false;
                throw;
            }
            return _response;
        }

        [HttpPost]
        [Route("api/StockOutAPIController/GetStockOut_Defective_ChallanList")]
        public async Task<Response> GetStockOut_Defective_ChallanList(StockTransferOutDOA_DefectiveSearchParameters parameters)
        {
            try
            {
                List<GetStockOut_Defective_ChallanList_Result> advanceList = new List<GetStockOut_Defective_ChallanList_Result>();
                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                if (userId > 0)
                {
                    advanceList = db.GetStockOut_Defective_ChallanList(parameters.ComapnyId, parameters.BranchFromId, parameters.DockerNo, userId).ToList();
                }

                _response.Data = advanceList;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }

        [HttpPost]
        [Route("api/StockTransferAPI/GetStockOut_Defective_ByChallanNumber")]
        public Response GetStockOut_Defective_ByChallanNumber(string ChallanNo = "")
        {
            try
            {
                var stockTransferResponse = new StockOutResponse();

                var userId = Convert.ToInt32(ActionContext.Request.Properties["UserId"] ?? 0);
                if (userId > 0)
                {
                    var vStockTransferOutObj = db.GetStockOutDefectiveByChallanNumber(ChallanNo).FirstOrDefault();

                    if (vStockTransferOutObj != null)
                    {
                        var vCompaniesObj = db.tblCompanies.Where(x => x.Id == vStockTransferOutObj.ComapnyId).FirstOrDefault();

                        stockTransferResponse.Id = vStockTransferOutObj.Id;
                        stockTransferResponse.ChallanNo = vStockTransferOutObj.ChallanNo;
                        stockTransferResponse.CompanyId = vStockTransferOutObj.ComapnyId;
                        stockTransferResponse.CompanyName = vCompaniesObj != null ? vCompaniesObj.CompanyName : string.Empty;
                        stockTransferResponse.BranchFromId = vStockTransferOutObj.BranchFromId;
                        stockTransferResponse.BranchFromName = vStockTransferOutObj.BranchFromName;
                        stockTransferResponse.BranchToId = vStockTransferOutObj.BranchToId;
                        stockTransferResponse.BranchToName = vStockTransferOutObj.BranchToName;
                        stockTransferResponse.TransferDate = vStockTransferOutObj.TransferDate;
                        stockTransferResponse.NewDocketNo = vStockTransferOutObj.NewDocketNo;
                        stockTransferResponse.StockTransferOutDate = vStockTransferOutObj.StockTransferOutDate;

                        stockTransferResponse.CreatedBy = vStockTransferOutObj.CreatedBy;
                        stockTransferResponse.CreatorName = vStockTransferOutObj.CreatorName;
                        stockTransferResponse.CreatedDate = vStockTransferOutObj.CreatedDate;


                        var vStockTransferOutPartDetailList = db.tblStockOut_Defective_PartDetails.Where(x => x.StockOut_DefectiveId == vStockTransferOutObj.Id).ToList();

                        foreach (var item in vStockTransferOutPartDetailList)
                        {
                            var vPartDetailsObj = db.tblPartDetails.Where(x => x.Id == item.PartId).FirstOrDefault();

                            var vItemObj = new StockOutPartDetailResponse()
                            {
                                Id = item.Id,
                                StockTransferOutId = item.StockOut_DefectiveId,
                                DocketNo = item.DocketNo,
                                PartId = item.PartId,
                                PartName = vPartDetailsObj != null ? vPartDetailsObj.PartName : string.Empty,
                            };

                            stockTransferResponse.PartsDetail.Add(vItemObj);
                        }
                    }
                }

                _response.Data = stockTransferResponse;
            }
            catch (Exception ex)
            {
                _response.IsSuccess = false;
                _response.Message = ValidationConstant.InternalServerError;
                LogWriter.WriteLog(ex);
            }

            return _response;
        }
    }
}
